package lib

import "time"

type AuthSuccess struct {
	UniqueID           string `json:"unique_id,omitempty"`
	FirstName          string `json:"first_name,omitempty"`
	LastName           string `json:"last_name,omitempty"`
	FullName           string `json:"full_name,omitempty"`
	Email              string `json:"email,omitempty"`
	EmailStatus        string `json:"email_status,omitempty"`
	EmailIsNull        bool   `json:"email_is_null,omitempty"`
	Phone              string `json:"phone,omitempty"`
	AvatarRelativePath string `json:"avatar_relative_path,omitempty"`
	AvatarRpath2       string `json:"avatar_rpath2,omitempty"`
	Status             string `json:"status,omitempty"`
	EmployeeNumber     string `json:"employee_number,omitempty"`
	CreateTime         int    `json:"create_time,omitempty"`
	Extras             struct {
	} `json:"extras,omitempty"`
	Username          string `json:"username,omitempty"`
	LocalAccountExist bool   `json:"local_account_exist,omitempty"`
	PasswordRevision  int    `json:"password_revision,omitempty"`
	SsoAccount        string `json:"sso_account,omitempty"`
	SsoUUID           string `json:"sso_uuid,omitempty"`
	SsoUsername       string `json:"sso_username,omitempty"`
	SsoPicture        string `json:"sso_picture,omitempty"`
	UIDSsoID          string `json:"uid_sso_id,omitempty"`
	UIDSsoAccount     string `json:"uid_sso_account,omitempty"`
	Groups            []struct {
		UniqueID   string        `json:"unique_id,omitempty"`
		Name       string        `json:"name,omitempty"`
		UpID       string        `json:"up_id,omitempty"`
		UpIds      []interface{} `json:"up_ids,omitempty"`
		SystemName string        `json:"system_name,omitempty"`
		CreateTime string        `json:"create_time,omitempty"`
	} `json:"groups,omitempty"`
	Roles []struct {
		UniqueID   string `json:"unique_id,omitempty"`
		Name       string `json:"name,omitempty"`
		SystemRole bool   `json:"system_role,omitempty"`
		SystemKey  string `json:"system_key,omitempty"`
		Level      int    `json:"level,omitempty"`
		CreateTime string `json:"create_time,omitempty"`
		UpdateTime string `json:"update_time,omitempty"`
	} `json:"roles,omitempty"`
	Permissions struct {
		AccessManagement         []string `json:"access.management,omitempty"`
		ConnectManagement        []string `json:"connect.management,omitempty"`
		LedManagement            []string `json:"led.management,omitempty"`
		NetworkManagement        []string `json:"network.management,omitempty"`
		ProtectManagement        []string `json:"protect.management,omitempty"`
		SystemManagementLocation []string `json:"system.management.location,omitempty"`
		SystemManagementUser     []string `json:"system.management.user,omitempty"`
		TalkManagement           []string `json:"talk.management,omitempty"`
	} `json:"permissions,omitempty"`
	Scopes             []string    `json:"scopes,omitempty"`
	CloudAccessGranted bool        `json:"cloud_access_granted,omitempty"`
	UpdateTime         int         `json:"update_time,omitempty"`
	Avatar             interface{} `json:"avatar,omitempty"`
	NfcToken           string      `json:"nfc_token,omitempty"`
	NfcDisplayID       string      `json:"nfc_display_id,omitempty"`
	NfcCardType        string      `json:"nfc_card_type,omitempty"`
	NfcCardStatus      string      `json:"nfc_card_status,omitempty"`
	ID                 string      `json:"id,omitempty"`
	IsOwner            bool        `json:"isOwner,omitempty"`
	IsSuperAdmin       bool        `json:"isSuperAdmin,omitempty"`
	IsMember           bool        `json:"isMember,omitempty"`
	UcorePermission    struct {
		HasViewUserPermission         bool `json:"hasViewUserPermission,omitempty"`
		HasEditUserPermission         bool `json:"hasEditUserPermission,omitempty"`
		HasViewSettingsPermission     bool `json:"hasViewSettingsPermission,omitempty"`
		HasUpdateChannelPermission    bool `json:"hasUpdateChannelPermission,omitempty"`
		HasGeneralSettingsPermission  bool `json:"hasGeneralSettingsPermission,omitempty"`
		HasUpdateAndInstallPermission bool `json:"hasUpdateAndInstallPermission,omitempty"`
		HasAutoUpdatePermission       bool `json:"hasAutoUpdatePermission,omitempty"`
		HasNotificationPermission     bool `json:"hasNotificationPermission,omitempty"`
		HasRemoteAccessPermission     bool `json:"hasRemoteAccessPermission,omitempty"`
		HasBackupPermission           bool `json:"hasBackupPermission,omitempty"`
		HasRestartConsolePermission   bool `json:"hasRestartConsolePermission,omitempty"`
		HasPoweroffConsolePermission  bool `json:"hasPoweroffConsolePermission,omitempty"`
		HasResetConsolePermission     bool `json:"hasResetConsolePermission,omitempty"`
		HasTransferOwnerPermission    bool `json:"hasTransferOwnerPermission,omitempty"`
		HasSSHPermission              bool `json:"hasSSHPermission,omitempty"`
		HasSupportFilePermission      bool `json:"hasSupportFilePermission,omitempty"`
	} `json:"ucorePermission,omitempty"`
	DeviceToken string `json:"deviceToken,omitempty"`
	SsoAuth     struct {
	} `json:"ssoAuth,omitempty"`
}
type AuthDetails struct {
	username string
	password string
}
type SwitchDetails struct {
	Meta struct {
		Rc string `json:"rc,omitempty"`
	} `json:"meta,omitempty"`
	Data []struct {
		ID            string `json:"_id,omitempty"`
		IP            string `json:"ip,omitempty"`
		Mac           string `json:"mac,omitempty"`
		Model         string `json:"model,omitempty"`
		ModelInLts    bool   `json:"model_in_lts,omitempty"`
		ModelInEol    bool   `json:"model_in_eol,omitempty"`
		Type          string `json:"type,omitempty"`
		Version       string `json:"version,omitempty"`
		Adopted       bool   `json:"adopted,omitempty"`
		SiteID        string `json:"site_id,omitempty"`
		XAuthkey      string `json:"x_authkey,omitempty"`
		Cfgversion    string `json:"cfgversion,omitempty"`
		SyslogKey     string `json:"syslog_key,omitempty"`
		ConfigNetwork struct {
			Type    string `json:"type,omitempty"`
			IP      string `json:"ip,omitempty"`
			DNS1    string `json:"dns1,omitempty"`
			Netmask string `json:"netmask,omitempty"`
			DNS2    string `json:"dns2,omitempty"`
			Gateway string `json:"gateway,omitempty"`
		} `json:"config_network,omitempty"`
		SetupID                  string        `json:"setup_id,omitempty"`
		XVwirekey                string        `json:"x_vwirekey,omitempty"`
		VwireTable               []interface{} `json:"vwire_table,omitempty"`
		MeshStaVapEnabled        bool          `json:"mesh_sta_vap_enabled,omitempty"`
		Dot1XPortctrlEnabled     bool          `json:"dot1x_portctrl_enabled,omitempty"`
		LicenseState             string        `json:"license_state,omitempty"`
		TwoPhaseAdopt            bool          `json:"two_phase_adopt,omitempty"`
		Unsupported              bool          `json:"unsupported,omitempty"`
		UnsupportedReason        int           `json:"unsupported_reason,omitempty"`
		AdoptedByClient          string        `json:"adopted_by_client,omitempty"`
		XSSHHostkeyFingerprint   string        `json:"x_ssh_hostkey_fingerprint,omitempty"`
		AdoptionCompleted        bool          `json:"adoption_completed,omitempty"`
		InformURL                string        `json:"inform_url,omitempty"`
		InformIP                 string        `json:"inform_ip,omitempty"`
		RequiredVersion          string        `json:"required_version,omitempty"`
		KernelVersion            string        `json:"kernel_version,omitempty"`
		Architecture             string        `json:"architecture,omitempty"`
		BoardRev                 int           `json:"board_rev,omitempty"`
		ManufacturerID           int           `json:"manufacturer_id,omitempty"`
		ModelIncompatible        bool          `json:"model_incompatible,omitempty"`
		DeviceID                 string        `json:"device_id,omitempty"`
		State                    int           `json:"state,omitempty"`
		StartDisconnectedMillis  int64         `json:"start_disconnected_millis,omitempty"`
		Serial                   string        `json:"serial,omitempty"`
		HashID                   string        `json:"hash_id,omitempty"`
		GatewayMac               string        `json:"gateway_mac,omitempty"`
		AnonID                   string        `json:"anon_id,omitempty"`
		LastSeen                 int           `json:"last_seen,omitempty"`
		XAesGcm                  bool          `json:"x_aes_gcm,omitempty"`
		MinInformIntervalSeconds int           `json:"min_inform_interval_seconds,omitempty"`
		Upgradable               bool          `json:"upgradable,omitempty"`
		AdoptableWhenUpgraded    bool          `json:"adoptable_when_upgraded,omitempty"`
		Rollupgrade              bool          `json:"rollupgrade,omitempty"`
		NextInterval             int           `json:"next_interval,omitempty"`
		AntennaTable             []struct {
			Default   bool   `json:"default,omitempty"`
			ID        int    `json:"id,omitempty"`
			Name      string `json:"name,omitempty"`
			Wifi0Gain int    `json:"wifi0_gain,omitempty"`
			Wifi1Gain int    `json:"wifi1_gain,omitempty"`
		} `json:"antenna_table,omitempty"`
		RadioTable []struct {
			Radio              string `json:"radio,omitempty"`
			MinTxpower         int    `json:"min_txpower,omitempty"`
			MaxTxpower         int    `json:"max_txpower,omitempty"`
			BuiltinAntenna     bool   `json:"builtin_antenna,omitempty"`
			BuiltinAntGain     int    `json:"builtin_ant_gain,omitempty"`
			CurrentAntennaGain int    `json:"current_antenna_gain,omitempty"`
			Nss                int    `json:"nss,omitempty"`
			Name               string `json:"name,omitempty"`
			Is11Ac             bool   `json:"is_11ac,omitempty"`
			Is11Ax             bool   `json:"is_11ax,omitempty"`
			RadioCaps          int    `json:"radio_caps,omitempty"`
			RadioCaps2         int    `json:"radio_caps2,omitempty"`
			Ht                 string `json:"ht,omitempty"`
			Channel            int    `json:"channel,omitempty"`
			BackupChannel      int    `json:"backup_channel,omitempty"`
			HasDfs             bool   `json:"has_dfs,omitempty"`
			HasFccdfs          bool   `json:"has_fccdfs,omitempty"`
			HasHt160           bool   `json:"has_ht160,omitempty"`
		} `json:"radio_table,omitempty"`
		ScanRadioTable []interface{} `json:"scan_radio_table,omitempty"`
		EthernetTable  []struct {
			Mac     string `json:"mac,omitempty"`
			NumPort int    `json:"num_port,omitempty"`
			Name    string `json:"name,omitempty"`
		} `json:"ethernet_table,omitempty"`
		PortTable  []interface{} `json:"port_table,omitempty"`
		SwitchCaps struct {
		} `json:"switch_caps,omitempty"`
		HasSpeaker            bool   `json:"has_speaker,omitempty"`
		HasEth1               bool   `json:"has_eth1,omitempty"`
		FwCaps                int    `json:"fw_caps,omitempty"`
		HwCaps                int    `json:"hw_caps,omitempty"`
		WifiCaps              int    `json:"wifi_caps,omitempty"`
		SysErrorCaps          int    `json:"sys_error_caps,omitempty"`
		HasFan                bool   `json:"has_fan,omitempty"`
		HasTemperature        bool   `json:"has_temperature,omitempty"`
		CountryCode           int    `json:"country_code,omitempty"`
		CountrycodeTable      []int  `json:"countrycode_table,omitempty"`
		SupportsFingerprintMl bool   `json:"supports_fingerprint_ml,omitempty"`
		KnownCfgversion       string `json:"known_cfgversion,omitempty"`
		StartConnectedMillis  int64  `json:"start_connected_millis,omitempty"`
		Uptime                int    `json:"uptime,omitempty"`
		Uptime0               int    `json:"_uptime,omitempty"`
		Locating              bool   `json:"locating,omitempty"`
		ProvisionedAt         int    `json:"provisioned_at,omitempty"`
		LastUplink            struct {
			UplinkMac        string `json:"uplink_mac,omitempty"`
			UplinkRemotePort int    `json:"uplink_remote_port,omitempty"`
			PortIdx          int    `json:"port_idx,omitempty"`
			Type             string `json:"type,omitempty"`
		} `json:"last_uplink,omitempty"`
		SysStats struct {
			Loadavg1  string `json:"loadavg_1,omitempty"`
			Loadavg15 string `json:"loadavg_15,omitempty"`
			Loadavg5  string `json:"loadavg_5,omitempty"`
			MemBuffer int    `json:"mem_buffer,omitempty"`
			MemTotal  int    `json:"mem_total,omitempty"`
			MemUsed   int    `json:"mem_used,omitempty"`
		} `json:"sys_stats,omitempty"`
		SystemStats struct {
			CPU    string `json:"cpu,omitempty"`
			Mem    string `json:"mem,omitempty"`
			Uptime string `json:"uptime,omitempty"`
		} `json:"system-stats,omitempty"`
		SSHSessionTable []interface{} `json:"ssh_session_table,omitempty"`
		LldpTable       []struct {
			ChassisDescr  string `json:"chassis_descr,omitempty"`
			ChassisID     string `json:"chassis_id,omitempty"`
			IsWired       bool   `json:"is_wired,omitempty"`
			LocalPortIdx  int    `json:"local_port_idx,omitempty"`
			LocalPortName string `json:"local_port_name,omitempty"`
			PortDescr     string `json:"port_descr,omitempty"`
			PortID        string `json:"port_id,omitempty"`
		} `json:"lldp_table,omitempty"`
		DisplayableVersion    string `json:"displayable_version,omitempty"`
		ConnectionNetworkName string `json:"connection_network_name,omitempty"`
		StartupTimestamp      int    `json:"startup_timestamp,omitempty"`
		IsAccessPoint         bool   `json:"is_access_point,omitempty"`
		Scanning              bool   `json:"scanning,omitempty"`
		SpectrumScanning      bool   `json:"spectrum_scanning,omitempty"`
		Meshv3PeerMac         string `json:"meshv3_peer_mac,omitempty"`
		ElementPeerMac        string `json:"element_peer_mac,omitempty"`
		GuestKicks            int    `json:"guest_kicks,omitempty"`
		GuestToken            string `json:"guest_token,omitempty"`
		Satisfaction          int    `json:"satisfaction,omitempty"`
		HideChWidth           string `json:"hide_ch_width,omitempty"`
		Isolated              bool   `json:"isolated,omitempty"`
		RadioTableStats       []struct {
			Name         string      `json:"name,omitempty"`
			Channel      int         `json:"channel,omitempty"`
			Radio        string      `json:"radio,omitempty"`
			AstTxto      interface{} `json:"ast_txto,omitempty"`
			AstCst       interface{} `json:"ast_cst,omitempty"`
			AstBeXmit    interface{} `json:"ast_be_xmit,omitempty"`
			CuTotal      int         `json:"cu_total,omitempty"`
			CuSelfRx     int         `json:"cu_self_rx,omitempty"`
			CuSelfTx     int         `json:"cu_self_tx,omitempty"`
			Gain         int         `json:"gain,omitempty"`
			Satisfaction int         `json:"satisfaction,omitempty"`
			State        string      `json:"state,omitempty"`
			Extchannel   int         `json:"extchannel,omitempty"`
			TxPower      int         `json:"tx_power,omitempty"`
			TxPackets    int         `json:"tx_packets,omitempty"`
			TxRetries    int         `json:"tx_retries,omitempty"`
			NumSta       int         `json:"num_sta,omitempty"`
			GuestNumSta  int         `json:"guest-num_sta,omitempty"`
			UserNumSta   int         `json:"user-num_sta,omitempty"`
		} `json:"radio_table_stats,omitempty"`
		Uplink struct {
			FullDuplex       bool   `json:"full_duplex,omitempty"`
			IP               string `json:"ip,omitempty"`
			Mac              string `json:"mac,omitempty"`
			Name             string `json:"name,omitempty"`
			Netmask          string `json:"netmask,omitempty"`
			NumPort          int    `json:"num_port,omitempty"`
			RxBytes          int64  `json:"rx_bytes,omitempty"`
			RxDropped        int    `json:"rx_dropped,omitempty"`
			RxErrors         int    `json:"rx_errors,omitempty"`
			RxMulticast      int    `json:"rx_multicast,omitempty"`
			RxPackets        int    `json:"rx_packets,omitempty"`
			Speed            int    `json:"speed,omitempty"`
			TxBytes          int64  `json:"tx_bytes,omitempty"`
			TxDropped        int    `json:"tx_dropped,omitempty"`
			TxErrors         int    `json:"tx_errors,omitempty"`
			TxPackets        int    `json:"tx_packets,omitempty"`
			Up               bool   `json:"up,omitempty"`
			MaxSpeed         int    `json:"max_speed,omitempty"`
			Type             string `json:"type,omitempty"`
			TxBytesR         int    `json:"tx_bytes-r,omitempty"`
			RxBytesR         int    `json:"rx_bytes-r,omitempty"`
			UplinkMac        string `json:"uplink_mac,omitempty"`
			UplinkRemotePort int    `json:"uplink_remote_port,omitempty"`
			UplinkSource     string `json:"uplink_source,omitempty"`
			PortIdx          int    `json:"port_idx,omitempty"`
			UplinkDeviceName string `json:"uplink_device_name,omitempty"`
		} `json:"uplink,omitempty"`
		VapTable []struct {
			AnomaliesBarChart struct {
				HighDisconnectCount int `json:"high_disconnect_count,omitempty"`
				HighDNSLatency      int `json:"high_dns_latency,omitempty"`
				HighIcmpRtt         int `json:"high_icmp_rtt,omitempty"`
				HighTCPLatency      int `json:"high_tcp_latency,omitempty"`
				HighTCPPacketLoss   int `json:"high_tcp_packet_loss,omitempty"`
				HighWifiLatency     int `json:"high_wifi_latency,omitempty"`
				HighWifiRetries     int `json:"high_wifi_retries,omitempty"`
				LowPhyRate          int `json:"low_phy_rate,omitempty"`
				NoDhcpResponse      int `json:"no_dhcp_response,omitempty"`
				PoorStreamEff       int `json:"poor_stream_eff,omitempty"`
				SleepyClient        int `json:"sleepy_client,omitempty"`
				StaArpTimeout       int `json:"sta_arp_timeout,omitempty"`
				StaDNSTimeout       int `json:"sta_dns_timeout,omitempty"`
				StaIPTimeout        int `json:"sta_ip_timeout,omitempty"`
				WeakSignal          int `json:"weak_signal,omitempty"`
			} `json:"anomalies_bar_chart,omitempty"`
			AnomaliesBarChartNow struct {
				HighDisconnectCount int `json:"high_disconnect_count,omitempty"`
				HighDNSLatency      int `json:"high_dns_latency,omitempty"`
				HighIcmpRtt         int `json:"high_icmp_rtt,omitempty"`
				HighTCPLatency      int `json:"high_tcp_latency,omitempty"`
				HighTCPPacketLoss   int `json:"high_tcp_packet_loss,omitempty"`
				HighWifiLatency     int `json:"high_wifi_latency,omitempty"`
				HighWifiRetries     int `json:"high_wifi_retries,omitempty"`
				LowPhyRate          int `json:"low_phy_rate,omitempty"`
				NoDhcpResponse      int `json:"no_dhcp_response,omitempty"`
				PoorStreamEff       int `json:"poor_stream_eff,omitempty"`
				SleepyClient        int `json:"sleepy_client,omitempty"`
				StaArpTimeout       int `json:"sta_arp_timeout,omitempty"`
				StaDNSTimeout       int `json:"sta_dns_timeout,omitempty"`
				StaIPTimeout        int `json:"sta_ip_timeout,omitempty"`
				WeakSignal          int `json:"weak_signal,omitempty"`
			} `json:"anomalies_bar_chart_now,omitempty"`
			AvgClientSignal     int    `json:"avg_client_signal,omitempty"`
			Bssid               string `json:"bssid,omitempty"`
			Bw                  int    `json:"bw,omitempty"`
			Ccq                 int    `json:"ccq,omitempty"`
			Channel             int    `json:"channel,omitempty"`
			DNSAvgLatency       int    `json:"dns_avg_latency,omitempty"`
			Essid               string `json:"essid,omitempty"`
			Extchannel          int    `json:"extchannel,omitempty"`
			IcmpAvgRtt          int    `json:"icmp_avg_rtt,omitempty"`
			ID                  string `json:"id,omitempty"`
			MacFilterRejections int    `json:"mac_filter_rejections,omitempty"`
			Name                string `json:"name,omitempty"`
			NumSatisfactionSta  int    `json:"num_satisfaction_sta,omitempty"`
			NumSta              int    `json:"num_sta,omitempty"`
			Radio               string `json:"radio,omitempty"`
			RadioName           string `json:"radio_name,omitempty"`
			ReasonsBarChart     struct {
				NoDhcpResponse int `json:"no_dhcp_response,omitempty"`
				PhyRate        int `json:"phy_rate,omitempty"`
				Signal         int `json:"signal,omitempty"`
				SleepyClient   int `json:"sleepy_client,omitempty"`
				StaArpTimeout  int `json:"sta_arp_timeout,omitempty"`
				StaDisconnects int `json:"sta_disconnects,omitempty"`
				StaDNSLatency  int `json:"sta_dns_latency,omitempty"`
				StaDNSTimeout  int `json:"sta_dns_timeout,omitempty"`
				StaIcmpRtt     int `json:"sta_icmp_rtt,omitempty"`
				StaIPTimeout   int `json:"sta_ip_timeout,omitempty"`
				StreamEff      int `json:"stream_eff,omitempty"`
				TCPLatency     int `json:"tcp_latency,omitempty"`
				TCPPacketLoss  int `json:"tcp_packet_loss,omitempty"`
				WifiLatency    int `json:"wifi_latency,omitempty"`
				WifiRetries    int `json:"wifi_retries,omitempty"`
			} `json:"reasons_bar_chart,omitempty"`
			ReasonsBarChartNow struct {
				NoDhcpResponse int `json:"no_dhcp_response,omitempty"`
				PhyRate        int `json:"phy_rate,omitempty"`
				Signal         int `json:"signal,omitempty"`
				SleepyClient   int `json:"sleepy_client,omitempty"`
				StaArpTimeout  int `json:"sta_arp_timeout,omitempty"`
				StaDisconnects int `json:"sta_disconnects,omitempty"`
				StaDNSLatency  int `json:"sta_dns_latency,omitempty"`
				StaDNSTimeout  int `json:"sta_dns_timeout,omitempty"`
				StaIcmpRtt     int `json:"sta_icmp_rtt,omitempty"`
				StaIPTimeout   int `json:"sta_ip_timeout,omitempty"`
				StreamEff      int `json:"stream_eff,omitempty"`
				TCPLatency     int `json:"tcp_latency,omitempty"`
				TCPPacketLoss  int `json:"tcp_packet_loss,omitempty"`
				WifiLatency    int `json:"wifi_latency,omitempty"`
				WifiRetries    int `json:"wifi_retries,omitempty"`
			} `json:"reasons_bar_chart_now,omitempty"`
			RxBytes    int64 `json:"rx_bytes,omitempty"`
			RxCrypts   int   `json:"rx_crypts,omitempty"`
			RxDropped  int   `json:"rx_dropped,omitempty"`
			RxErrors   int   `json:"rx_errors,omitempty"`
			RxFrags    int   `json:"rx_frags,omitempty"`
			RxNwids    int   `json:"rx_nwids,omitempty"`
			RxPackets  int   `json:"rx_packets,omitempty"`
			RxTCPStats struct {
				Goodbytes  int `json:"goodbytes,omitempty"`
				LatAvg     int `json:"lat_avg,omitempty"`
				LatMax     int `json:"lat_max,omitempty"`
				LatMin     int `json:"lat_min,omitempty"`
				LatSamples int `json:"lat_samples,omitempty"`
				LatSum     int `json:"lat_sum,omitempty"`
				Retries    int `json:"retries,omitempty"`
				Stalls     int `json:"stalls,omitempty"`
			} `json:"rx_tcp_stats,omitempty"`
			Satisfaction      int    `json:"satisfaction,omitempty"`
			State             string `json:"state,omitempty"`
			TxBytes           int64  `json:"tx_bytes,omitempty"`
			TxCombinedRetries int    `json:"tx_combined_retries,omitempty"`
			TxDataMpduBytes   int    `json:"tx_data_mpdu_bytes,omitempty"`
			TxDropped         int    `json:"tx_dropped,omitempty"`
			TxErrors          int    `json:"tx_errors,omitempty"`
			TxPackets         int    `json:"tx_packets,omitempty"`
			TxPower           int    `json:"tx_power,omitempty"`
			TxRetries         int    `json:"tx_retries,omitempty"`
			TxRtsRetries      int    `json:"tx_rts_retries,omitempty"`
			TxSuccess         int    `json:"tx_success,omitempty"`
			TxTCPStats        struct {
				Goodbytes  int `json:"goodbytes,omitempty"`
				LatAvg     int `json:"lat_avg,omitempty"`
				LatMax     int `json:"lat_max,omitempty"`
				LatMin     int `json:"lat_min,omitempty"`
				LatSamples int `json:"lat_samples,omitempty"`
				LatSum     int `json:"lat_sum,omitempty"`
				Retries    int `json:"retries,omitempty"`
				Stalls     int `json:"stalls,omitempty"`
			} `json:"tx_tcp_stats,omitempty"`
			TxTotal          int    `json:"tx_total,omitempty"`
			Up               bool   `json:"up,omitempty"`
			Usage            string `json:"usage,omitempty"`
			WifiTxAttempts   int    `json:"wifi_tx_attempts,omitempty"`
			WifiTxDropped    int    `json:"wifi_tx_dropped,omitempty"`
			T                string `json:"t,omitempty"`
			WlanconfID       string `json:"wlanconf_id,omitempty"`
			IsGuest          bool   `json:"is_guest,omitempty"`
			IsWep            bool   `json:"is_wep,omitempty"`
			ApMac            string `json:"ap_mac,omitempty"`
			MapID            string `json:"map_id,omitempty"`
			SiteID           string `json:"site_id,omitempty"`
			WifiTxLatencyMov struct {
				Avg        int `json:"avg,omitempty"`
				Max        int `json:"max,omitempty"`
				Min        int `json:"min,omitempty"`
				Total      int `json:"total,omitempty"`
				TotalCount int `json:"total_count,omitempty"`
			} `json:"wifi_tx_latency_mov,omitempty"`
		} `json:"vap_table,omitempty"`
		DownlinkTable []interface{} `json:"downlink_table,omitempty"`
		VwireVapTable []struct {
			State     string `json:"state,omitempty"`
			Radio     string `json:"radio,omitempty"`
			RadioName string `json:"radio_name,omitempty"`
			Bssid     string `json:"bssid,omitempty"`
		} `json:"vwire_vap_table,omitempty"`
		BytesD                     int     `json:"bytes-d,omitempty"`
		TxBytesD                   int     `json:"tx_bytes-d,omitempty"`
		RxBytesD                   int     `json:"rx_bytes-d,omitempty"`
		BytesR                     int     `json:"bytes-r,omitempty"`
		LedOverride                string  `json:"led_override,omitempty"`
		LedOverrideColor           string  `json:"led_override_color,omitempty"`
		LedOverrideColorBrightness int     `json:"led_override_color_brightness,omitempty"`
		OutdoorModeOverride        string  `json:"outdoor_mode_override,omitempty"`
		LcmBrightnessOverride      bool    `json:"lcm_brightness_override,omitempty"`
		LcmIdleTimeoutOverride     bool    `json:"lcm_idle_timeout_override,omitempty"`
		Name                       string  `json:"name,omitempty"`
		Internet                   bool    `json:"internet,omitempty"`
		PrevNonBusyState           int     `json:"prev_non_busy_state,omitempty"`
		LastScan                   int     `json:"last_scan,omitempty"`
		MapID                      string  `json:"map_id,omitempty"`
		X                          float64 `json:"x,omitempty"`
		Y                          float64 `json:"y,omitempty"`
		HeightInMeters             float64 `json:"heightInMeters,omitempty"`
		ConnectRequestIP           string  `json:"connect_request_ip,omitempty"`
		ConnectRequestPort         string  `json:"connect_request_port,omitempty"`
		UpgradeToFirmware          string  `json:"upgrade_to_firmware,omitempty"`
		Stat                       struct {
			Ap struct {
				SiteID                                               string    `json:"site_id,omitempty"`
				O                                                    string    `json:"o,omitempty"`
				Oid                                                  string    `json:"oid,omitempty"`
				Ap                                                   string    `json:"ap,omitempty"`
				Time                                                 int64     `json:"time,omitempty"`
				Datetime                                             time.Time `json:"datetime,omitempty"`
				GuestWifi0RxPackets                                  float64   `json:"guest-wifi0-rx_packets,omitempty"`
				GuestWifi1RxPackets                                  int       `json:"guest-wifi1-rx_packets,omitempty"`
				UserWifi1RxPackets                                   float64   `json:"user-wifi1-rx_packets,omitempty"`
				UserWifi0RxPackets                                   float64   `json:"user-wifi0-rx_packets,omitempty"`
				UserRxPackets                                        float64   `json:"user-rx_packets,omitempty"`
				GuestRxPackets                                       int       `json:"guest-rx_packets,omitempty"`
				Wifi0RxPackets                                       float64   `json:"wifi0-rx_packets,omitempty"`
				Wifi1RxPackets                                       int       `json:"wifi1-rx_packets,omitempty"`
				RxPackets                                            int       `json:"rx_packets,omitempty"`
				GuestWifi0RxBytes                                    int64     `json:"guest-wifi0-rx_bytes,omitempty"`
				GuestWifi1RxBytes                                    int64     `json:"guest-wifi1-rx_bytes,omitempty"`
				UserWifi1RxBytes                                     int       `json:"user-wifi1-rx_bytes,omitempty"`
				UserWifi0RxBytes                                     int       `json:"user-wifi0-rx_bytes,omitempty"`
				UserRxBytes                                          int       `json:"user-rx_bytes,omitempty"`
				GuestRxBytes                                         int64     `json:"guest-rx_bytes,omitempty"`
				Wifi0RxBytes                                         int64     `json:"wifi0-rx_bytes,omitempty"`
				Wifi1RxBytes                                         int64     `json:"wifi1-rx_bytes,omitempty"`
				RxBytes                                              int64     `json:"rx_bytes,omitempty"`
				GuestWifi0RxErrors                                   float64   `json:"guest-wifi0-rx_errors,omitempty"`
				GuestWifi1RxErrors                                   float64   `json:"guest-wifi1-rx_errors,omitempty"`
				UserWifi1RxErrors                                    float64   `json:"user-wifi1-rx_errors,omitempty"`
				UserWifi0RxErrors                                    float64   `json:"user-wifi0-rx_errors,omitempty"`
				UserRxErrors                                         float64   `json:"user-rx_errors,omitempty"`
				GuestRxErrors                                        float64   `json:"guest-rx_errors,omitempty"`
				Wifi0RxErrors                                        float64   `json:"wifi0-rx_errors,omitempty"`
				Wifi1RxErrors                                        float64   `json:"wifi1-rx_errors,omitempty"`
				RxErrors                                             float64   `json:"rx_errors,omitempty"`
				GuestWifi0RxDropped                                  float64   `json:"guest-wifi0-rx_dropped,omitempty"`
				GuestWifi1RxDropped                                  float64   `json:"guest-wifi1-rx_dropped,omitempty"`
				UserWifi1RxDropped                                   float64   `json:"user-wifi1-rx_dropped,omitempty"`
				UserWifi0RxDropped                                   float64   `json:"user-wifi0-rx_dropped,omitempty"`
				UserRxDropped                                        float64   `json:"user-rx_dropped,omitempty"`
				GuestRxDropped                                       float64   `json:"guest-rx_dropped,omitempty"`
				Wifi0RxDropped                                       float64   `json:"wifi0-rx_dropped,omitempty"`
				Wifi1RxDropped                                       float64   `json:"wifi1-rx_dropped,omitempty"`
				RxDropped                                            float64   `json:"rx_dropped,omitempty"`
				GuestWifi0RxCrypts                                   float64   `json:"guest-wifi0-rx_crypts,omitempty"`
				GuestWifi1RxCrypts                                   float64   `json:"guest-wifi1-rx_crypts,omitempty"`
				UserWifi1RxCrypts                                    float64   `json:"user-wifi1-rx_crypts,omitempty"`
				UserWifi0RxCrypts                                    float64   `json:"user-wifi0-rx_crypts,omitempty"`
				UserRxCrypts                                         float64   `json:"user-rx_crypts,omitempty"`
				GuestRxCrypts                                        float64   `json:"guest-rx_crypts,omitempty"`
				Wifi0RxCrypts                                        float64   `json:"wifi0-rx_crypts,omitempty"`
				Wifi1RxCrypts                                        float64   `json:"wifi1-rx_crypts,omitempty"`
				RxCrypts                                             float64   `json:"rx_crypts,omitempty"`
				GuestWifi0RxFrags                                    float64   `json:"guest-wifi0-rx_frags,omitempty"`
				GuestWifi1RxFrags                                    float64   `json:"guest-wifi1-rx_frags,omitempty"`
				UserWifi1RxFrags                                     float64   `json:"user-wifi1-rx_frags,omitempty"`
				UserWifi0RxFrags                                     float64   `json:"user-wifi0-rx_frags,omitempty"`
				UserRxFrags                                          float64   `json:"user-rx_frags,omitempty"`
				GuestRxFrags                                         float64   `json:"guest-rx_frags,omitempty"`
				Wifi0RxFrags                                         float64   `json:"wifi0-rx_frags,omitempty"`
				Wifi1RxFrags                                         float64   `json:"wifi1-rx_frags,omitempty"`
				RxFrags                                              float64   `json:"rx_frags,omitempty"`
				GuestWifi0TxPackets                                  float64   `json:"guest-wifi0-tx_packets,omitempty"`
				GuestWifi1TxPackets                                  int       `json:"guest-wifi1-tx_packets,omitempty"`
				UserWifi1TxPackets                                   int       `json:"user-wifi1-tx_packets,omitempty"`
				UserWifi0TxPackets                                   float64   `json:"user-wifi0-tx_packets,omitempty"`
				UserTxPackets                                        int       `json:"user-tx_packets,omitempty"`
				GuestTxPackets                                       int       `json:"guest-tx_packets,omitempty"`
				Wifi0TxPackets                                       float64   `json:"wifi0-tx_packets,omitempty"`
				Wifi1TxPackets                                       int       `json:"wifi1-tx_packets,omitempty"`
				TxPackets                                            int       `json:"tx_packets,omitempty"`
				GuestWifi0TxBytes                                    int64     `json:"guest-wifi0-tx_bytes,omitempty"`
				GuestWifi1TxBytes                                    int64     `json:"guest-wifi1-tx_bytes,omitempty"`
				UserWifi1TxBytes                                     int64     `json:"user-wifi1-tx_bytes,omitempty"`
				UserWifi0TxBytes                                     int       `json:"user-wifi0-tx_bytes,omitempty"`
				UserTxBytes                                          int64     `json:"user-tx_bytes,omitempty"`
				GuestTxBytes                                         int64     `json:"guest-tx_bytes,omitempty"`
				Wifi0TxBytes                                         int64     `json:"wifi0-tx_bytes,omitempty"`
				Wifi1TxBytes                                         int64     `json:"wifi1-tx_bytes,omitempty"`
				TxBytes                                              int64     `json:"tx_bytes,omitempty"`
				GuestWifi0TxErrors                                   float64   `json:"guest-wifi0-tx_errors,omitempty"`
				GuestWifi1TxErrors                                   float64   `json:"guest-wifi1-tx_errors,omitempty"`
				UserWifi1TxErrors                                    float64   `json:"user-wifi1-tx_errors,omitempty"`
				UserWifi0TxErrors                                    float64   `json:"user-wifi0-tx_errors,omitempty"`
				UserTxErrors                                         float64   `json:"user-tx_errors,omitempty"`
				GuestTxErrors                                        float64   `json:"guest-tx_errors,omitempty"`
				Wifi0TxErrors                                        float64   `json:"wifi0-tx_errors,omitempty"`
				Wifi1TxErrors                                        float64   `json:"wifi1-tx_errors,omitempty"`
				TxErrors                                             float64   `json:"tx_errors,omitempty"`
				GuestWifi0TxDropped                                  float64   `json:"guest-wifi0-tx_dropped,omitempty"`
				GuestWifi1TxDropped                                  float64   `json:"guest-wifi1-tx_dropped,omitempty"`
				UserWifi1TxDropped                                   float64   `json:"user-wifi1-tx_dropped,omitempty"`
				UserWifi0TxDropped                                   float64   `json:"user-wifi0-tx_dropped,omitempty"`
				UserTxDropped                                        float64   `json:"user-tx_dropped,omitempty"`
				GuestTxDropped                                       float64   `json:"guest-tx_dropped,omitempty"`
				Wifi0TxDropped                                       float64   `json:"wifi0-tx_dropped,omitempty"`
				Wifi1TxDropped                                       float64   `json:"wifi1-tx_dropped,omitempty"`
				TxDropped                                            float64   `json:"tx_dropped,omitempty"`
				GuestWifi0TxRetries                                  float64   `json:"guest-wifi0-tx_retries,omitempty"`
				GuestWifi1TxRetries                                  int64     `json:"guest-wifi1-tx_retries,omitempty"`
				UserWifi1TxRetries                                   float64   `json:"user-wifi1-tx_retries,omitempty"`
				UserWifi0TxRetries                                   float64   `json:"user-wifi0-tx_retries,omitempty"`
				UserTxRetries                                        float64   `json:"user-tx_retries,omitempty"`
				GuestTxRetries                                       int64     `json:"guest-tx_retries,omitempty"`
				Wifi0TxRetries                                       float64   `json:"wifi0-tx_retries,omitempty"`
				Wifi1TxRetries                                       int64     `json:"wifi1-tx_retries,omitempty"`
				TxRetries                                            int64     `json:"tx_retries,omitempty"`
				GuestWifi0MacFilterRejections                        float64   `json:"guest-wifi0-mac_filter_rejections,omitempty"`
				GuestWifi1MacFilterRejections                        float64   `json:"guest-wifi1-mac_filter_rejections,omitempty"`
				UserWifi1MacFilterRejections                         float64   `json:"user-wifi1-mac_filter_rejections,omitempty"`
				UserWifi0MacFilterRejections                         float64   `json:"user-wifi0-mac_filter_rejections,omitempty"`
				UserMacFilterRejections                              float64   `json:"user-mac_filter_rejections,omitempty"`
				GuestMacFilterRejections                             float64   `json:"guest-mac_filter_rejections,omitempty"`
				Wifi0MacFilterRejections                             float64   `json:"wifi0-mac_filter_rejections,omitempty"`
				Wifi1MacFilterRejections                             float64   `json:"wifi1-mac_filter_rejections,omitempty"`
				MacFilterRejections                                  float64   `json:"mac_filter_rejections,omitempty"`
				GuestWifi0WifiTxAttempts                             float64   `json:"guest-wifi0-wifi_tx_attempts,omitempty"`
				GuestWifi1WifiTxAttempts                             int       `json:"guest-wifi1-wifi_tx_attempts,omitempty"`
				UserWifi1WifiTxAttempts                              float64   `json:"user-wifi1-wifi_tx_attempts,omitempty"`
				UserWifi0WifiTxAttempts                              float64   `json:"user-wifi0-wifi_tx_attempts,omitempty"`
				UserWifiTxAttempts                                   float64   `json:"user-wifi_tx_attempts,omitempty"`
				GuestWifiTxAttempts                                  int       `json:"guest-wifi_tx_attempts,omitempty"`
				Wifi0WifiTxAttempts                                  float64   `json:"wifi0-wifi_tx_attempts,omitempty"`
				Wifi1WifiTxAttempts                                  int       `json:"wifi1-wifi_tx_attempts,omitempty"`
				WifiTxAttempts                                       int       `json:"wifi_tx_attempts,omitempty"`
				GuestWifi0WifiTxDropped                              float64   `json:"guest-wifi0-wifi_tx_dropped,omitempty"`
				GuestWifi1WifiTxDropped                              float64   `json:"guest-wifi1-wifi_tx_dropped,omitempty"`
				UserWifi1WifiTxDropped                               float64   `json:"user-wifi1-wifi_tx_dropped,omitempty"`
				UserWifi0WifiTxDropped                               float64   `json:"user-wifi0-wifi_tx_dropped,omitempty"`
				UserWifiTxDropped                                    float64   `json:"user-wifi_tx_dropped,omitempty"`
				GuestWifiTxDropped                                   float64   `json:"guest-wifi_tx_dropped,omitempty"`
				Wifi0WifiTxDropped                                   float64   `json:"wifi0-wifi_tx_dropped,omitempty"`
				Wifi1WifiTxDropped                                   float64   `json:"wifi1-wifi_tx_dropped,omitempty"`
				WifiTxDropped                                        float64   `json:"wifi_tx_dropped,omitempty"`
				NaWifiTxAttempts                                     int       `json:"na-wifi_tx_attempts,omitempty"`
				NgWifiTxAttempts                                     float64   `json:"ng-wifi_tx_attempts,omitempty"`
				NaWifiTxDropped                                      float64   `json:"na-wifi_tx_dropped,omitempty"`
				NgWifiTxDropped                                      float64   `json:"ng-wifi_tx_dropped,omitempty"`
				NaTxRetries                                          int64     `json:"na-tx_retries,omitempty"`
				NgTxRetries                                          float64   `json:"ng-tx_retries,omitempty"`
				NaTxPackets                                          int       `json:"na-tx_packets,omitempty"`
				NgTxPackets                                          float64   `json:"ng-tx_packets,omitempty"`
				NaTxBytes                                            int64     `json:"na-tx_bytes,omitempty"`
				NgTxBytes                                            int64     `json:"ng-tx_bytes,omitempty"`
				Bytes                                                int64     `json:"bytes,omitempty"`
				Duration                                             int       `json:"duration,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988TxDropped      float64   `json:"guest-wifi1-ath6-633202311a24a10969173988-tx_dropped,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2TxDropped       float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-tx_dropped,omitempty"`
				UserWifi0Ath2632A08E01A24A1078C5F89D7TxDropped       float64   `json:"user-wifi0-ath2-632a08e01a24a1078c5f89d7-tx_dropped,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988TxDropped      float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-tx_dropped,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2TxDropped       float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-tx_dropped,omitempty"`
				UserWifi1Ath7632A08E01A24A1078C5F89D7TxDropped       float64   `json:"user-wifi1-ath7-632a08e01a24a1078c5f89d7-tx_dropped,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2RxPackets       float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-rx_packets,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2RxBytes         int       `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-rx_bytes,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2TxPackets       int       `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-tx_packets,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2TxBytes         int64     `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-tx_bytes,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2WifiTxAttempts  float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-wifi_tx_attempts,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2RxPackets       float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-rx_packets,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2RxBytes         int       `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-rx_bytes,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2TxPackets       float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-tx_packets,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2TxBytes         int       `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-tx_bytes,omitempty"`
				NumWifiConnectEvents                                 float64   `json:"num_wifi_connect_events,omitempty"`
				NaNumWifiConnectEvents                               float64   `json:"na-num_wifi_connect_events,omitempty"`
				NumWifiDisconnectEvents                              float64   `json:"num_wifi_disconnect_events,omitempty"`
				NaNumWifiDisconnectEvents                            float64   `json:"na-num_wifi_disconnect_events,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2TxRetries       float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-tx_retries,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2TxRetries       float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-tx_retries,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2WifiTxAttempts  float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-wifi_tx_attempts,omitempty"`
				NgNumWifiConnectEvents                               float64   `json:"ng-num_wifi_connect_events,omitempty"`
				NgNumWifiDisconnectEvents                            float64   `json:"ng-num_wifi_disconnect_events,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2TxErrors        float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-tx_errors,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2TxErrors        float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-tx_errors,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2WifiTxDropped   float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-wifi_tx_dropped,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2WifiTxDropped   float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-wifi_tx_dropped,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2RxErrors        float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-rx_errors,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2RxDropped       float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-rx_dropped,omitempty"`
				UserWifi0Ath06331E4Fb1A24A1095025E0D2RxCrypts        float64   `json:"user-wifi0-ath0-6331e4fb1a24a1095025e0d2-rx_crypts,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2RxErrors        float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-rx_errors,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2RxDropped       float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-rx_dropped,omitempty"`
				UserWifi1Ath56331E4Fb1A24A1095025E0D2RxCrypts        float64   `json:"user-wifi1-ath5-6331e4fb1a24a1095025e0d2-rx_crypts,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988RxPackets      int       `json:"guest-wifi1-ath6-633202311a24a10969173988-rx_packets,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988RxBytes        int64     `json:"guest-wifi1-ath6-633202311a24a10969173988-rx_bytes,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988TxPackets      int       `json:"guest-wifi1-ath6-633202311a24a10969173988-tx_packets,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988TxBytes        int64     `json:"guest-wifi1-ath6-633202311a24a10969173988-tx_bytes,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988TxRetries      int64     `json:"guest-wifi1-ath6-633202311a24a10969173988-tx_retries,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988WifiTxAttempts int       `json:"guest-wifi1-ath6-633202311a24a10969173988-wifi_tx_attempts,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988RxPackets      float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-rx_packets,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988RxBytes        int64     `json:"guest-wifi0-ath1-633202311a24a10969173988-rx_bytes,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988TxPackets      float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-tx_packets,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988TxBytes        int64     `json:"guest-wifi0-ath1-633202311a24a10969173988-tx_bytes,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988TxRetries      float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-tx_retries,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988WifiTxAttempts float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-wifi_tx_attempts,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988TxErrors       float64   `json:"guest-wifi1-ath6-633202311a24a10969173988-tx_errors,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988WifiTxDropped  float64   `json:"guest-wifi1-ath6-633202311a24a10969173988-wifi_tx_dropped,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988TxErrors       float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-tx_errors,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988WifiTxDropped  float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-wifi_tx_dropped,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988RxErrors       float64   `json:"guest-wifi1-ath6-633202311a24a10969173988-rx_errors,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988RxDropped      float64   `json:"guest-wifi1-ath6-633202311a24a10969173988-rx_dropped,omitempty"`
				GuestWifi1Ath6633202311A24A10969173988RxCrypts       float64   `json:"guest-wifi1-ath6-633202311a24a10969173988-rx_crypts,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988RxErrors       float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-rx_errors,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988RxDropped      float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-rx_dropped,omitempty"`
				GuestWifi0Ath1633202311A24A10969173988RxCrypts       float64   `json:"guest-wifi0-ath1-633202311a24a10969173988-rx_crypts,omitempty"`
			} `json:"ap,omitempty"`
		} `json:"stat,omitempty"`
		TxBytes         int64         `json:"tx_bytes,omitempty"`
		RxBytes         int64         `json:"rx_bytes,omitempty"`
		Bytes           int64         `json:"bytes,omitempty"`
		VwireEnabled    bool          `json:"vwireEnabled,omitempty"`
		UplinkTable     []interface{} `json:"uplink_table,omitempty"`
		NumSta          int           `json:"num_sta,omitempty"`
		UserNumSta      int           `json:"user-num_sta,omitempty"`
		UserWlanNumSta  int           `json:"user-wlan-num_sta,omitempty"`
		GuestNumSta     int           `json:"guest-num_sta,omitempty"`
		GuestWlanNumSta int           `json:"guest-wlan-num_sta,omitempty"`
		XHasSSHHostkey  bool          `json:"x_has_ssh_hostkey,omitempty"`
		Default         bool          `json:"default,omitempty"`
		DiscoveredVia   string        `json:"discovered_via,omitempty"`
		AdoptIP         string        `json:"adopt_ip,omitempty"`
		AdoptURL        string        `json:"adopt_url,omitempty"`
		Watching        bool          `json:"watching,omitempty"`
		WatchingTimeout int           `json:"watching_timeout,omitempty"`
		ConfigNetwork0  struct {
			Type string `json:"type,omitempty"`
			IP   string `json:"ip,omitempty"`
		} `json:"config_network,omitempty"`
		ConnectedAt      int  `json:"connected_at,omitempty"`
		FixedApAvailable bool `json:"fixed_ap_available,omitempty"`
		AdopterTable     []struct {
			LastSeen     int    `json:"last_seen,omitempty"`
			Rssi         int    `json:"rssi,omitempty"`
			ApMac        string `json:"ap_mac,omitempty"`
			IsMeshv3     bool   `json:"is_meshv3,omitempty"`
			Radio        string `json:"radio,omitempty"`
			VwireEnabled bool   `json:"vwire_enabled,omitempty"`
			Bw           int    `json:"bw,omitempty"`
			Freq         int    `json:"freq,omitempty"`
		} `json:"adopter_table,omitempty"`
		AdoptStatus    int    `json:"adopt_status,omitempty"`
		UpgradeState   int    `json:"upgrade_state,omitempty"`
		AdoptState     int    `json:"adopt_state,omitempty"`
		AdoptTries     int    `json:"adopt_tries,omitempty"`
		AdoptManual    bool   `json:"adopt_manual,omitempty"`
		XAdoptUsername string `json:"x_adopt_username,omitempty"`
		XAdoptPassword string `json:"x_adopt_password,omitempty"`
		AtfEnabled     bool   `json:"atf_enabled,omitempty"`
		ConfigNetwork1 struct {
			Type           string `json:"type,omitempty"`
			IP             string `json:"ip,omitempty"`
			Netmask        string `json:"netmask,omitempty"`
			Gateway        string `json:"gateway,omitempty"`
			DNS1           string `json:"dns1,omitempty"`
			DNS2           string `json:"dns2,omitempty"`
			Dnssuffix      string `json:"dnssuffix,omitempty"`
			BondingEnabled bool   `json:"bonding_enabled,omitempty"`
		} `json:"config_network,omitempty"`
		JumboframeEnabled      bool   `json:"jumboframe_enabled,omitempty"`
		FlowctrlEnabled        bool   `json:"flowctrl_enabled,omitempty"`
		StpVersion             string `json:"stp_version,omitempty"`
		StpPriority            string `json:"stp_priority,omitempty"`
		PowerSourceCtrlEnabled bool   `json:"power_source_ctrl_enabled,omitempty"`
		SwitchCaps0            struct {
			FeatureCaps          int `json:"feature_caps,omitempty"`
			MaxMirrorSessions    int `json:"max_mirror_sessions,omitempty"`
			MaxAggregateSessions int `json:"max_aggregate_sessions,omitempty"`
			MaxL3Intf            int `json:"max_l3_intf,omitempty"`
			MaxReservedRoutes    int `json:"max_reserved_routes,omitempty"`
			MaxStaticRoutes      int `json:"max_static_routes,omitempty"`
		} `json:"switch_caps,omitempty"`
		Anomalies     int `json:"anomalies,omitempty"`
		PortOverrides []struct {
			PortIdx                int           `json:"port_idx,omitempty"`
			PortconfID             string        `json:"portconf_id,omitempty"`
			PortSecurityMacAddress []interface{} `json:"port_security_mac_address,omitempty"`
			Name                   string        `json:"name,omitempty"`
		} `json:"port_overrides,omitempty"`
		Uplink0 struct {
			FullDuplex   bool   `json:"full_duplex,omitempty"`
			IP           string `json:"ip,omitempty"`
			Mac          string `json:"mac,omitempty"`
			Name         string `json:"name,omitempty"`
			Netmask      string `json:"netmask,omitempty"`
			NumPort      int    `json:"num_port,omitempty"`
			RxBytes      int    `json:"rx_bytes,omitempty"`
			RxDropped    int    `json:"rx_dropped,omitempty"`
			RxErrors     int    `json:"rx_errors,omitempty"`
			RxMulticast  int    `json:"rx_multicast,omitempty"`
			RxPackets    int    `json:"rx_packets,omitempty"`
			Speed        int    `json:"speed,omitempty"`
			TxBytes      int    `json:"tx_bytes,omitempty"`
			TxDropped    int    `json:"tx_dropped,omitempty"`
			TxErrors     int    `json:"tx_errors,omitempty"`
			TxPackets    int    `json:"tx_packets,omitempty"`
			Up           bool   `json:"up,omitempty"`
			MaxSpeed     int    `json:"max_speed,omitempty"`
			Type         string `json:"type,omitempty"`
			TxBytesR     int    `json:"tx_bytes-r,omitempty"`
			RxBytesR     int    `json:"rx_bytes-r,omitempty"`
			UplinkSource string `json:"uplink_source,omitempty"`
		} `json:"uplink,omitempty"`
		FanLevel           int           `json:"fan_level,omitempty"`
		GeneralTemperature int           `json:"general_temperature,omitempty"`
		Overheating        bool          `json:"overheating,omitempty"`
		TotalMaxPower      int           `json:"total_max_power,omitempty"`
		DhcpServerTable    []interface{} `json:"dhcp_server_table,omitempty"`
		Stat0              struct {
			Sw struct {
				SiteID            string    `json:"site_id,omitempty"`
				O                 string    `json:"o,omitempty"`
				Oid               string    `json:"oid,omitempty"`
				Sw                string    `json:"sw,omitempty"`
				Time              int64     `json:"time,omitempty"`
				Datetime          time.Time `json:"datetime,omitempty"`
				RxPackets         int       `json:"rx_packets,omitempty"`
				RxBytes           int64     `json:"rx_bytes,omitempty"`
				RxErrors          float64   `json:"rx_errors,omitempty"`
				RxDropped         float64   `json:"rx_dropped,omitempty"`
				RxCrypts          float64   `json:"rx_crypts,omitempty"`
				RxFrags           float64   `json:"rx_frags,omitempty"`
				TxPackets         int       `json:"tx_packets,omitempty"`
				TxBytes           int64     `json:"tx_bytes,omitempty"`
				TxErrors          float64   `json:"tx_errors,omitempty"`
				TxDropped         float64   `json:"tx_dropped,omitempty"`
				TxRetries         float64   `json:"tx_retries,omitempty"`
				RxMulticast       float64   `json:"rx_multicast,omitempty"`
				RxBroadcast       float64   `json:"rx_broadcast,omitempty"`
				TxMulticast       int       `json:"tx_multicast,omitempty"`
				TxBroadcast       int       `json:"tx_broadcast,omitempty"`
				Bytes             int64     `json:"bytes,omitempty"`
				Duration          int       `json:"duration,omitempty"`
				Port1RxPackets    int       `json:"port_1-rx_packets,omitempty"`
				Port1RxBytes      int64     `json:"port_1-rx_bytes,omitempty"`
				Port1TxPackets    int       `json:"port_1-tx_packets,omitempty"`
				Port1TxBytes      int64     `json:"port_1-tx_bytes,omitempty"`
				Port1RxBroadcast  float64   `json:"port_1-rx_broadcast,omitempty"`
				Port1TxMulticast  float64   `json:"port_1-tx_multicast,omitempty"`
				Port1TxBroadcast  float64   `json:"port_1-tx_broadcast,omitempty"`
				Port2RxPackets    float64   `json:"port_2-rx_packets,omitempty"`
				Port2RxBytes      int       `json:"port_2-rx_bytes,omitempty"`
				Port2RxDropped    float64   `json:"port_2-rx_dropped,omitempty"`
				Port2TxPackets    float64   `json:"port_2-tx_packets,omitempty"`
				Port2TxBytes      int64     `json:"port_2-tx_bytes,omitempty"`
				Port2RxMulticast  float64   `json:"port_2-rx_multicast,omitempty"`
				Port2TxMulticast  float64   `json:"port_2-tx_multicast,omitempty"`
				Port2TxBroadcast  float64   `json:"port_2-tx_broadcast,omitempty"`
				Port7RxPackets    float64   `json:"port_7-rx_packets,omitempty"`
				Port7RxBytes      int       `json:"port_7-rx_bytes,omitempty"`
				Port7RxDropped    float64   `json:"port_7-rx_dropped,omitempty"`
				Port7TxPackets    int       `json:"port_7-tx_packets,omitempty"`
				Port7TxBytes      int       `json:"port_7-tx_bytes,omitempty"`
				Port7RxMulticast  float64   `json:"port_7-rx_multicast,omitempty"`
				Port7RxBroadcast  float64   `json:"port_7-rx_broadcast,omitempty"`
				Port7TxMulticast  float64   `json:"port_7-tx_multicast,omitempty"`
				Port7TxBroadcast  float64   `json:"port_7-tx_broadcast,omitempty"`
				Port8RxPackets    float64   `json:"port_8-rx_packets,omitempty"`
				Port8RxBytes      int       `json:"port_8-rx_bytes,omitempty"`
				Port8TxPackets    int       `json:"port_8-tx_packets,omitempty"`
				Port8TxBytes      int       `json:"port_8-tx_bytes,omitempty"`
				Port8RxBroadcast  float64   `json:"port_8-rx_broadcast,omitempty"`
				Port8TxMulticast  float64   `json:"port_8-tx_multicast,omitempty"`
				Port8TxBroadcast  float64   `json:"port_8-tx_broadcast,omitempty"`
				Port10TxPackets   float64   `json:"port_10-tx_packets,omitempty"`
				Port10TxBytes     int       `json:"port_10-tx_bytes,omitempty"`
				Port10TxMulticast float64   `json:"port_10-tx_multicast,omitempty"`
				Port10TxBroadcast float64   `json:"port_10-tx_broadcast,omitempty"`
				Port12RxPackets   float64   `json:"port_12-rx_packets,omitempty"`
				Port12RxBytes     int       `json:"port_12-rx_bytes,omitempty"`
				Port12RxDropped   float64   `json:"port_12-rx_dropped,omitempty"`
				Port12TxPackets   float64   `json:"port_12-tx_packets,omitempty"`
				Port12TxBytes     int       `json:"port_12-tx_bytes,omitempty"`
				Port12RxMulticast float64   `json:"port_12-rx_multicast,omitempty"`
				Port12TxMulticast float64   `json:"port_12-tx_multicast,omitempty"`
				Port12TxBroadcast float64   `json:"port_12-tx_broadcast,omitempty"`
				Port14RxPackets   float64   `json:"port_14-rx_packets,omitempty"`
				Port14RxBytes     int       `json:"port_14-rx_bytes,omitempty"`
				Port14RxDropped   float64   `json:"port_14-rx_dropped,omitempty"`
				Port14TxPackets   float64   `json:"port_14-tx_packets,omitempty"`
				Port14TxBytes     int       `json:"port_14-tx_bytes,omitempty"`
				Port14RxMulticast float64   `json:"port_14-rx_multicast,omitempty"`
				Port14TxMulticast float64   `json:"port_14-tx_multicast,omitempty"`
				Port14TxBroadcast float64   `json:"port_14-tx_broadcast,omitempty"`
				Port20RxPackets   float64   `json:"port_20-rx_packets,omitempty"`
				Port20RxBytes     int       `json:"port_20-rx_bytes,omitempty"`
				Port20RxDropped   float64   `json:"port_20-rx_dropped,omitempty"`
				Port20TxPackets   float64   `json:"port_20-tx_packets,omitempty"`
				Port20TxBytes     int       `json:"port_20-tx_bytes,omitempty"`
				Port20RxMulticast float64   `json:"port_20-rx_multicast,omitempty"`
				Port20TxMulticast float64   `json:"port_20-tx_multicast,omitempty"`
				Port20TxBroadcast float64   `json:"port_20-tx_broadcast,omitempty"`
				Port21RxPackets   float64   `json:"port_21-rx_packets,omitempty"`
				Port21RxBytes     int       `json:"port_21-rx_bytes,omitempty"`
				Port21RxDropped   float64   `json:"port_21-rx_dropped,omitempty"`
				Port21TxPackets   float64   `json:"port_21-tx_packets,omitempty"`
				Port21TxBytes     int       `json:"port_21-tx_bytes,omitempty"`
				Port21RxMulticast float64   `json:"port_21-rx_multicast,omitempty"`
				Port21TxMulticast float64   `json:"port_21-tx_multicast,omitempty"`
				Port21TxBroadcast float64   `json:"port_21-tx_broadcast,omitempty"`
				Port22RxPackets   float64   `json:"port_22-rx_packets,omitempty"`
				Port22RxBytes     int       `json:"port_22-rx_bytes,omitempty"`
				Port22RxDropped   float64   `json:"port_22-rx_dropped,omitempty"`
				Port22TxPackets   float64   `json:"port_22-tx_packets,omitempty"`
				Port22TxBytes     int       `json:"port_22-tx_bytes,omitempty"`
				Port22RxMulticast float64   `json:"port_22-rx_multicast,omitempty"`
				Port22TxMulticast float64   `json:"port_22-tx_multicast,omitempty"`
				Port22TxBroadcast float64   `json:"port_22-tx_broadcast,omitempty"`
				Port23RxPackets   float64   `json:"port_23-rx_packets,omitempty"`
				Port23RxBytes     int       `json:"port_23-rx_bytes,omitempty"`
				Port23RxDropped   float64   `json:"port_23-rx_dropped,omitempty"`
				Port23TxPackets   float64   `json:"port_23-tx_packets,omitempty"`
				Port23TxBytes     int       `json:"port_23-tx_bytes,omitempty"`
				Port23RxMulticast float64   `json:"port_23-rx_multicast,omitempty"`
				Port23TxMulticast float64   `json:"port_23-tx_multicast,omitempty"`
				Port23TxBroadcast float64   `json:"port_23-tx_broadcast,omitempty"`
				Port24RxPackets   float64   `json:"port_24-rx_packets,omitempty"`
				Port24RxBytes     int       `json:"port_24-rx_bytes,omitempty"`
				Port24RxDropped   float64   `json:"port_24-rx_dropped,omitempty"`
				Port24TxPackets   float64   `json:"port_24-tx_packets,omitempty"`
				Port24TxBytes     int64     `json:"port_24-tx_bytes,omitempty"`
				Port24RxMulticast float64   `json:"port_24-rx_multicast,omitempty"`
				Port24TxMulticast float64   `json:"port_24-tx_multicast,omitempty"`
				Port24TxBroadcast float64   `json:"port_24-tx_broadcast,omitempty"`
				Port27RxPackets   float64   `json:"port_27-rx_packets,omitempty"`
				Port27RxBytes     int       `json:"port_27-rx_bytes,omitempty"`
				Port27RxDropped   float64   `json:"port_27-rx_dropped,omitempty"`
				Port27TxPackets   float64   `json:"port_27-tx_packets,omitempty"`
				Port27TxBytes     int       `json:"port_27-tx_bytes,omitempty"`
				Port27RxMulticast float64   `json:"port_27-rx_multicast,omitempty"`
				Port27TxMulticast float64   `json:"port_27-tx_multicast,omitempty"`
				Port27TxBroadcast float64   `json:"port_27-tx_broadcast,omitempty"`
				Port31RxPackets   float64   `json:"port_31-rx_packets,omitempty"`
				Port31RxBytes     int       `json:"port_31-rx_bytes,omitempty"`
				Port31RxDropped   float64   `json:"port_31-rx_dropped,omitempty"`
				Port31TxPackets   float64   `json:"port_31-tx_packets,omitempty"`
				Port31TxBytes     int       `json:"port_31-tx_bytes,omitempty"`
				Port31RxMulticast float64   `json:"port_31-rx_multicast,omitempty"`
				Port31TxMulticast float64   `json:"port_31-tx_multicast,omitempty"`
				Port31TxBroadcast float64   `json:"port_31-tx_broadcast,omitempty"`
				Port32RxPackets   float64   `json:"port_32-rx_packets,omitempty"`
				Port32RxBytes     int       `json:"port_32-rx_bytes,omitempty"`
				Port32TxPackets   float64   `json:"port_32-tx_packets,omitempty"`
				Port32TxBytes     int       `json:"port_32-tx_bytes,omitempty"`
				Port32RxMulticast float64   `json:"port_32-rx_multicast,omitempty"`
				Port32RxBroadcast float64   `json:"port_32-rx_broadcast,omitempty"`
				Port32TxMulticast float64   `json:"port_32-tx_multicast,omitempty"`
				Port32TxBroadcast float64   `json:"port_32-tx_broadcast,omitempty"`
				Port34RxPackets   float64   `json:"port_34-rx_packets,omitempty"`
				Port34RxBytes     int       `json:"port_34-rx_bytes,omitempty"`
				Port34RxDropped   float64   `json:"port_34-rx_dropped,omitempty"`
				Port34TxPackets   float64   `json:"port_34-tx_packets,omitempty"`
				Port34TxBytes     int       `json:"port_34-tx_bytes,omitempty"`
				Port34RxMulticast float64   `json:"port_34-rx_multicast,omitempty"`
				Port34TxMulticast float64   `json:"port_34-tx_multicast,omitempty"`
				Port34TxBroadcast float64   `json:"port_34-tx_broadcast,omitempty"`
				Port35RxPackets   int       `json:"port_35-rx_packets,omitempty"`
				Port35RxBytes     int       `json:"port_35-rx_bytes,omitempty"`
				Port35TxPackets   int       `json:"port_35-tx_packets,omitempty"`
				Port35TxBytes     int64     `json:"port_35-tx_bytes,omitempty"`
				Port35RxMulticast float64   `json:"port_35-rx_multicast,omitempty"`
				Port35RxBroadcast float64   `json:"port_35-rx_broadcast,omitempty"`
				Port35TxMulticast float64   `json:"port_35-tx_multicast,omitempty"`
				Port35TxBroadcast float64   `json:"port_35-tx_broadcast,omitempty"`
				Port36RxPackets   float64   `json:"port_36-rx_packets,omitempty"`
				Port36RxBytes     int       `json:"port_36-rx_bytes,omitempty"`
				Port36TxPackets   float64   `json:"port_36-tx_packets,omitempty"`
				Port36TxBytes     int       `json:"port_36-tx_bytes,omitempty"`
				Port36RxMulticast float64   `json:"port_36-rx_multicast,omitempty"`
				Port36RxBroadcast float64   `json:"port_36-rx_broadcast,omitempty"`
				Port36TxMulticast float64   `json:"port_36-tx_multicast,omitempty"`
				Port36TxBroadcast float64   `json:"port_36-tx_broadcast,omitempty"`
				Port37RxPackets   float64   `json:"port_37-rx_packets,omitempty"`
				Port37RxBytes     float64   `json:"port_37-rx_bytes,omitempty"`
				Port37RxDropped   float64   `json:"port_37-rx_dropped,omitempty"`
				Port37TxPackets   float64   `json:"port_37-tx_packets,omitempty"`
				Port37TxBytes     float64   `json:"port_37-tx_bytes,omitempty"`
				Port37RxMulticast float64   `json:"port_37-rx_multicast,omitempty"`
				Port37RxBroadcast float64   `json:"port_37-rx_broadcast,omitempty"`
				Port37TxMulticast float64   `json:"port_37-tx_multicast,omitempty"`
				Port37TxBroadcast float64   `json:"port_37-tx_broadcast,omitempty"`
				Port38RxPackets   int       `json:"port_38-rx_packets,omitempty"`
				Port38RxBytes     int64     `json:"port_38-rx_bytes,omitempty"`
				Port38RxDropped   float64   `json:"port_38-rx_dropped,omitempty"`
				Port38TxPackets   int       `json:"port_38-tx_packets,omitempty"`
				Port38TxBytes     int64     `json:"port_38-tx_bytes,omitempty"`
				Port38RxMulticast float64   `json:"port_38-rx_multicast,omitempty"`
				Port38RxBroadcast float64   `json:"port_38-rx_broadcast,omitempty"`
				Port38TxMulticast float64   `json:"port_38-tx_multicast,omitempty"`
				Port38TxBroadcast float64   `json:"port_38-tx_broadcast,omitempty"`
				Port39RxPackets   int       `json:"port_39-rx_packets,omitempty"`
				Port39RxBytes     int64     `json:"port_39-rx_bytes,omitempty"`
				Port39RxDropped   float64   `json:"port_39-rx_dropped,omitempty"`
				Port39TxPackets   int       `json:"port_39-tx_packets,omitempty"`
				Port39TxBytes     int64     `json:"port_39-tx_bytes,omitempty"`
				Port39RxMulticast float64   `json:"port_39-rx_multicast,omitempty"`
				Port39TxMulticast float64   `json:"port_39-tx_multicast,omitempty"`
				Port39TxBroadcast float64   `json:"port_39-tx_broadcast,omitempty"`
				Port40RxPackets   int       `json:"port_40-rx_packets,omitempty"`
				Port40RxBytes     int64     `json:"port_40-rx_bytes,omitempty"`
				Port40TxPackets   int       `json:"port_40-tx_packets,omitempty"`
				Port40TxBytes     int64     `json:"port_40-tx_bytes,omitempty"`
				Port40RxMulticast float64   `json:"port_40-rx_multicast,omitempty"`
				Port40RxBroadcast float64   `json:"port_40-rx_broadcast,omitempty"`
				Port40TxMulticast float64   `json:"port_40-tx_multicast,omitempty"`
				Port40TxBroadcast float64   `json:"port_40-tx_broadcast,omitempty"`
				Port41RxPackets   float64   `json:"port_41-rx_packets,omitempty"`
				Port41RxBytes     int       `json:"port_41-rx_bytes,omitempty"`
				Port41TxPackets   int       `json:"port_41-tx_packets,omitempty"`
				Port41TxBytes     int64     `json:"port_41-tx_bytes,omitempty"`
				Port41RxMulticast float64   `json:"port_41-rx_multicast,omitempty"`
				Port41RxBroadcast float64   `json:"port_41-rx_broadcast,omitempty"`
				Port41TxMulticast float64   `json:"port_41-tx_multicast,omitempty"`
				Port41TxBroadcast float64   `json:"port_41-tx_broadcast,omitempty"`
				Port42RxPackets   float64   `json:"port_42-rx_packets,omitempty"`
				Port42RxBytes     int       `json:"port_42-rx_bytes,omitempty"`
				Port42TxPackets   float64   `json:"port_42-tx_packets,omitempty"`
				Port42TxBytes     int       `json:"port_42-tx_bytes,omitempty"`
				Port42RxMulticast float64   `json:"port_42-rx_multicast,omitempty"`
				Port42RxBroadcast float64   `json:"port_42-rx_broadcast,omitempty"`
				Port42TxMulticast float64   `json:"port_42-tx_multicast,omitempty"`
				Port42TxBroadcast float64   `json:"port_42-tx_broadcast,omitempty"`
				Port43RxPackets   int       `json:"port_43-rx_packets,omitempty"`
				Port43RxBytes     int64     `json:"port_43-rx_bytes,omitempty"`
				Port43TxPackets   int       `json:"port_43-tx_packets,omitempty"`
				Port43TxBytes     int64     `json:"port_43-tx_bytes,omitempty"`
				Port43RxMulticast float64   `json:"port_43-rx_multicast,omitempty"`
				Port43RxBroadcast float64   `json:"port_43-rx_broadcast,omitempty"`
				Port43TxMulticast float64   `json:"port_43-tx_multicast,omitempty"`
				Port43TxBroadcast float64   `json:"port_43-tx_broadcast,omitempty"`
				Port44RxPackets   float64   `json:"port_44-rx_packets,omitempty"`
				Port44RxBytes     int       `json:"port_44-rx_bytes,omitempty"`
				Port44TxPackets   float64   `json:"port_44-tx_packets,omitempty"`
				Port44TxBytes     int       `json:"port_44-tx_bytes,omitempty"`
				Port44RxMulticast float64   `json:"port_44-rx_multicast,omitempty"`
				Port44RxBroadcast float64   `json:"port_44-rx_broadcast,omitempty"`
				Port44TxMulticast float64   `json:"port_44-tx_multicast,omitempty"`
				Port44TxBroadcast float64   `json:"port_44-tx_broadcast,omitempty"`
				Port46RxPackets   int       `json:"port_46-rx_packets,omitempty"`
				Port46RxBytes     int64     `json:"port_46-rx_bytes,omitempty"`
				Port46TxPackets   int       `json:"port_46-tx_packets,omitempty"`
				Port46TxBytes     int64     `json:"port_46-tx_bytes,omitempty"`
				Port46RxMulticast float64   `json:"port_46-rx_multicast,omitempty"`
				Port46RxBroadcast float64   `json:"port_46-rx_broadcast,omitempty"`
				Port46TxMulticast float64   `json:"port_46-tx_multicast,omitempty"`
				Port46TxBroadcast float64   `json:"port_46-tx_broadcast,omitempty"`
				Port48RxPackets   int       `json:"port_48-rx_packets,omitempty"`
				Port48RxBytes     int64     `json:"port_48-rx_bytes,omitempty"`
				Port48RxDropped   float64   `json:"port_48-rx_dropped,omitempty"`
				Port48TxPackets   int       `json:"port_48-tx_packets,omitempty"`
				Port48TxBytes     int64     `json:"port_48-tx_bytes,omitempty"`
				Port48RxMulticast float64   `json:"port_48-rx_multicast,omitempty"`
				Port48RxBroadcast float64   `json:"port_48-rx_broadcast,omitempty"`
				Port48TxMulticast float64   `json:"port_48-tx_multicast,omitempty"`
				Port48TxBroadcast float64   `json:"port_48-tx_broadcast,omitempty"`
				Port51RxPackets   int       `json:"port_51-rx_packets,omitempty"`
				Port51RxBytes     int64     `json:"port_51-rx_bytes,omitempty"`
				Port51RxDropped   float64   `json:"port_51-rx_dropped,omitempty"`
				Port51TxPackets   int       `json:"port_51-tx_packets,omitempty"`
				Port51TxBytes     int64     `json:"port_51-tx_bytes,omitempty"`
				Port51RxMulticast float64   `json:"port_51-rx_multicast,omitempty"`
				Port51RxBroadcast float64   `json:"port_51-rx_broadcast,omitempty"`
				Port51TxMulticast float64   `json:"port_51-tx_multicast,omitempty"`
				Port51TxBroadcast float64   `json:"port_51-tx_broadcast,omitempty"`
				Port2RxBroadcast  float64   `json:"port_2-rx_broadcast,omitempty"`
				Port8RxMulticast  float64   `json:"port_8-rx_multicast,omitempty"`
				Port10RxPackets   float64   `json:"port_10-rx_packets,omitempty"`
				Port10RxBytes     int       `json:"port_10-rx_bytes,omitempty"`
				Port10RxMulticast float64   `json:"port_10-rx_multicast,omitempty"`
				Port39RxBroadcast float64   `json:"port_39-rx_broadcast,omitempty"`
				Port40RxDropped   float64   `json:"port_40-rx_dropped,omitempty"`
				Port31TxDropped   float64   `json:"port_31-tx_dropped,omitempty"`
				Port12RxBroadcast float64   `json:"port_12-rx_broadcast,omitempty"`
				Port14RxBroadcast float64   `json:"port_14-rx_broadcast,omitempty"`
				Port20RxBroadcast float64   `json:"port_20-rx_broadcast,omitempty"`
				Port21RxBroadcast float64   `json:"port_21-rx_broadcast,omitempty"`
				Port22RxBroadcast float64   `json:"port_22-rx_broadcast,omitempty"`
				Port23RxBroadcast float64   `json:"port_23-rx_broadcast,omitempty"`
				Port24RxBroadcast float64   `json:"port_24-rx_broadcast,omitempty"`
				Port27RxBroadcast float64   `json:"port_27-rx_broadcast,omitempty"`
				Port31RxBroadcast float64   `json:"port_31-rx_broadcast,omitempty"`
				Port34RxBroadcast float64   `json:"port_34-rx_broadcast,omitempty"`
				Port41RxDropped   float64   `json:"port_41-rx_dropped,omitempty"`
				Port43RxDropped   float64   `json:"port_43-rx_dropped,omitempty"`
				Port8RxDropped    float64   `json:"port_8-rx_dropped,omitempty"`
				Port32RxDropped   float64   `json:"port_32-rx_dropped,omitempty"`
				Port35RxDropped   float64   `json:"port_35-rx_dropped,omitempty"`
				Port46RxDropped   float64   `json:"port_46-rx_dropped,omitempty"`
				Port10RxBroadcast float64   `json:"port_10-rx_broadcast,omitempty"`
				Port10RxDropped   float64   `json:"port_10-rx_dropped,omitempty"`
				Port36RxDropped   float64   `json:"port_36-rx_dropped,omitempty"`
				Port2TxDropped    float64   `json:"port_2-tx_dropped,omitempty"`
				Port40TxDropped   float64   `json:"port_40-tx_dropped,omitempty"`
				Port42RxDropped   float64   `json:"port_42-rx_dropped,omitempty"`
			} `json:"sw,omitempty"`
		} `json:"stat,omitempty"`
		DisconnectionReason string `json:"disconnection_reason,omitempty"`
		ConfigNetwork2      struct {
			Type           string `json:"type,omitempty"`
			IP             string `json:"ip,omitempty"`
			Netmask        string `json:"netmask,omitempty"`
			Gateway        string `json:"gateway,omitempty"`
			DNS1           string `json:"dns1,omitempty"`
			DNS2           string `json:"dns2,omitempty"`
			Dnssuffix      string `json:"dnssuffix,omitempty"`
			BondingEnabled bool   `json:"bonding_enabled,omitempty"`
		} `json:"config_network,omitempty"`
		SwitchCaps1 struct {
			FeatureCaps          int `json:"feature_caps,omitempty"`
			MaxMirrorSessions    int `json:"max_mirror_sessions,omitempty"`
			MaxAggregateSessions int `json:"max_aggregate_sessions,omitempty"`
			MaxL3Intf            int `json:"max_l3_intf,omitempty"`
			MaxReservedRoutes    int `json:"max_reserved_routes,omitempty"`
			MaxStaticRoutes      int `json:"max_static_routes,omitempty"`
		} `json:"switch_caps,omitempty"`
		Uplink1 struct {
			FullDuplex       bool   `json:"full_duplex,omitempty"`
			IP               string `json:"ip,omitempty"`
			Mac              string `json:"mac,omitempty"`
			Name             string `json:"name,omitempty"`
			Netmask          string `json:"netmask,omitempty"`
			NumPort          int    `json:"num_port,omitempty"`
			RxBytes          int64  `json:"rx_bytes,omitempty"`
			RxDropped        int    `json:"rx_dropped,omitempty"`
			RxErrors         int    `json:"rx_errors,omitempty"`
			RxMulticast      int    `json:"rx_multicast,omitempty"`
			RxPackets        int    `json:"rx_packets,omitempty"`
			Speed            int    `json:"speed,omitempty"`
			TxBytes          int64  `json:"tx_bytes,omitempty"`
			TxDropped        int    `json:"tx_dropped,omitempty"`
			TxErrors         int    `json:"tx_errors,omitempty"`
			TxPackets        int    `json:"tx_packets,omitempty"`
			Up               bool   `json:"up,omitempty"`
			PortIdx          int    `json:"port_idx,omitempty"`
			Media            string `json:"media,omitempty"`
			MaxSpeed         int    `json:"max_speed,omitempty"`
			UplinkMac        string `json:"uplink_mac,omitempty"`
			UplinkSource     string `json:"uplink_source,omitempty"`
			UplinkRemotePort int    `json:"uplink_remote_port,omitempty"`
			Type             string `json:"type,omitempty"`
			TxBytesR         int    `json:"tx_bytes-r,omitempty"`
			RxBytesR         int    `json:"rx_bytes-r,omitempty"`
			UplinkDeviceName string `json:"uplink_device_name,omitempty"`
		} `json:"uplink,omitempty"`
		UplinkDepth int `json:"uplink_depth,omitempty"`
		Stat1       struct {
			Sw struct {
				SiteID            string    `json:"site_id,omitempty"`
				O                 string    `json:"o,omitempty"`
				Oid               string    `json:"oid,omitempty"`
				Sw                string    `json:"sw,omitempty"`
				Time              int64     `json:"time,omitempty"`
				Datetime          time.Time `json:"datetime,omitempty"`
				RxPackets         int       `json:"rx_packets,omitempty"`
				RxBytes           int64     `json:"rx_bytes,omitempty"`
				RxErrors          float64   `json:"rx_errors,omitempty"`
				RxDropped         float64   `json:"rx_dropped,omitempty"`
				RxCrypts          float64   `json:"rx_crypts,omitempty"`
				RxFrags           float64   `json:"rx_frags,omitempty"`
				TxPackets         int       `json:"tx_packets,omitempty"`
				TxBytes           int64     `json:"tx_bytes,omitempty"`
				TxErrors          float64   `json:"tx_errors,omitempty"`
				TxDropped         float64   `json:"tx_dropped,omitempty"`
				TxRetries         float64   `json:"tx_retries,omitempty"`
				RxMulticast       float64   `json:"rx_multicast,omitempty"`
				RxBroadcast       float64   `json:"rx_broadcast,omitempty"`
				TxMulticast       int       `json:"tx_multicast,omitempty"`
				TxBroadcast       int       `json:"tx_broadcast,omitempty"`
				Bytes             int64     `json:"bytes,omitempty"`
				Duration          int       `json:"duration,omitempty"`
				Port7RxPackets    float64   `json:"port_7-rx_packets,omitempty"`
				Port7RxBytes      int       `json:"port_7-rx_bytes,omitempty"`
				Port7RxDropped    float64   `json:"port_7-rx_dropped,omitempty"`
				Port7TxPackets    float64   `json:"port_7-tx_packets,omitempty"`
				Port7TxBytes      int64     `json:"port_7-tx_bytes,omitempty"`
				Port7RxMulticast  float64   `json:"port_7-rx_multicast,omitempty"`
				Port7RxBroadcast  float64   `json:"port_7-rx_broadcast,omitempty"`
				Port7TxMulticast  float64   `json:"port_7-tx_multicast,omitempty"`
				Port7TxBroadcast  float64   `json:"port_7-tx_broadcast,omitempty"`
				Port9TxPackets    int       `json:"port_9-tx_packets,omitempty"`
				Port9TxBytes      int64     `json:"port_9-tx_bytes,omitempty"`
				Port9TxMulticast  float64   `json:"port_9-tx_multicast,omitempty"`
				Port9TxBroadcast  float64   `json:"port_9-tx_broadcast,omitempty"`
				Port10RxPackets   float64   `json:"port_10-rx_packets,omitempty"`
				Port10RxBytes     int       `json:"port_10-rx_bytes,omitempty"`
				Port10RxDropped   float64   `json:"port_10-rx_dropped,omitempty"`
				Port10TxPackets   float64   `json:"port_10-tx_packets,omitempty"`
				Port10TxBytes     int       `json:"port_10-tx_bytes,omitempty"`
				Port10RxMulticast float64   `json:"port_10-rx_multicast,omitempty"`
				Port10RxBroadcast float64   `json:"port_10-rx_broadcast,omitempty"`
				Port10TxMulticast float64   `json:"port_10-tx_multicast,omitempty"`
				Port10TxBroadcast float64   `json:"port_10-tx_broadcast,omitempty"`
				Port11RxPackets   int       `json:"port_11-rx_packets,omitempty"`
				Port11RxBytes     int64     `json:"port_11-rx_bytes,omitempty"`
				Port11RxDropped   float64   `json:"port_11-rx_dropped,omitempty"`
				Port11TxPackets   int       `json:"port_11-tx_packets,omitempty"`
				Port11TxBytes     int64     `json:"port_11-tx_bytes,omitempty"`
				Port11RxMulticast float64   `json:"port_11-rx_multicast,omitempty"`
				Port11RxBroadcast float64   `json:"port_11-rx_broadcast,omitempty"`
				Port11TxMulticast float64   `json:"port_11-tx_multicast,omitempty"`
				Port11TxBroadcast float64   `json:"port_11-tx_broadcast,omitempty"`
				Port12RxPackets   float64   `json:"port_12-rx_packets,omitempty"`
				Port12RxBytes     int       `json:"port_12-rx_bytes,omitempty"`
				Port12RxDropped   float64   `json:"port_12-rx_dropped,omitempty"`
				Port12TxPackets   int       `json:"port_12-tx_packets,omitempty"`
				Port12TxBytes     int       `json:"port_12-tx_bytes,omitempty"`
				Port12RxMulticast float64   `json:"port_12-rx_multicast,omitempty"`
				Port12RxBroadcast float64   `json:"port_12-rx_broadcast,omitempty"`
				Port12TxMulticast float64   `json:"port_12-tx_multicast,omitempty"`
				Port12TxBroadcast float64   `json:"port_12-tx_broadcast,omitempty"`
				Port13RxPackets   float64   `json:"port_13-rx_packets,omitempty"`
				Port13RxBytes     int64     `json:"port_13-rx_bytes,omitempty"`
				Port13RxDropped   float64   `json:"port_13-rx_dropped,omitempty"`
				Port13TxPackets   int       `json:"port_13-tx_packets,omitempty"`
				Port13TxBytes     int64     `json:"port_13-tx_bytes,omitempty"`
				Port13RxMulticast float64   `json:"port_13-rx_multicast,omitempty"`
				Port13RxBroadcast float64   `json:"port_13-rx_broadcast,omitempty"`
				Port13TxMulticast float64   `json:"port_13-tx_multicast,omitempty"`
				Port13TxBroadcast float64   `json:"port_13-tx_broadcast,omitempty"`
				Port16RxPackets   float64   `json:"port_16-rx_packets,omitempty"`
				Port16RxBytes     int       `json:"port_16-rx_bytes,omitempty"`
				Port16RxDropped   float64   `json:"port_16-rx_dropped,omitempty"`
				Port16TxPackets   int       `json:"port_16-tx_packets,omitempty"`
				Port16TxBytes     int       `json:"port_16-tx_bytes,omitempty"`
				Port16RxMulticast float64   `json:"port_16-rx_multicast,omitempty"`
				Port16RxBroadcast float64   `json:"port_16-rx_broadcast,omitempty"`
				Port16TxMulticast float64   `json:"port_16-tx_multicast,omitempty"`
				Port16TxBroadcast float64   `json:"port_16-tx_broadcast,omitempty"`
				Port18TxPackets   int       `json:"port_18-tx_packets,omitempty"`
				Port18TxBytes     int64     `json:"port_18-tx_bytes,omitempty"`
				Port18TxMulticast float64   `json:"port_18-tx_multicast,omitempty"`
				Port18TxBroadcast float64   `json:"port_18-tx_broadcast,omitempty"`
				Port19RxPackets   float64   `json:"port_19-rx_packets,omitempty"`
				Port19RxBytes     int       `json:"port_19-rx_bytes,omitempty"`
				Port19RxDropped   float64   `json:"port_19-rx_dropped,omitempty"`
				Port19TxPackets   int       `json:"port_19-tx_packets,omitempty"`
				Port19TxBytes     int       `json:"port_19-tx_bytes,omitempty"`
				Port19RxMulticast float64   `json:"port_19-rx_multicast,omitempty"`
				Port19RxBroadcast float64   `json:"port_19-rx_broadcast,omitempty"`
				Port19TxMulticast float64   `json:"port_19-tx_multicast,omitempty"`
				Port19TxBroadcast float64   `json:"port_19-tx_broadcast,omitempty"`
				Port21RxPackets   float64   `json:"port_21-rx_packets,omitempty"`
				Port21RxBytes     int64     `json:"port_21-rx_bytes,omitempty"`
				Port21RxDropped   float64   `json:"port_21-rx_dropped,omitempty"`
				Port21TxPackets   int       `json:"port_21-tx_packets,omitempty"`
				Port21TxBytes     int64     `json:"port_21-tx_bytes,omitempty"`
				Port21RxMulticast float64   `json:"port_21-rx_multicast,omitempty"`
				Port21RxBroadcast float64   `json:"port_21-rx_broadcast,omitempty"`
				Port21TxMulticast float64   `json:"port_21-tx_multicast,omitempty"`
				Port21TxBroadcast float64   `json:"port_21-tx_broadcast,omitempty"`
				Port22TxPackets   int       `json:"port_22-tx_packets,omitempty"`
				Port22TxBytes     int64     `json:"port_22-tx_bytes,omitempty"`
				Port22TxMulticast float64   `json:"port_22-tx_multicast,omitempty"`
				Port22TxBroadcast float64   `json:"port_22-tx_broadcast,omitempty"`
				Port23RxPackets   float64   `json:"port_23-rx_packets,omitempty"`
				Port23RxBytes     int       `json:"port_23-rx_bytes,omitempty"`
				Port23RxDropped   float64   `json:"port_23-rx_dropped,omitempty"`
				Port23TxPackets   int       `json:"port_23-tx_packets,omitempty"`
				Port23TxBytes     int64     `json:"port_23-tx_bytes,omitempty"`
				Port23RxMulticast float64   `json:"port_23-rx_multicast,omitempty"`
				Port23RxBroadcast float64   `json:"port_23-rx_broadcast,omitempty"`
				Port23TxMulticast float64   `json:"port_23-tx_multicast,omitempty"`
				Port23TxBroadcast float64   `json:"port_23-tx_broadcast,omitempty"`
				Port24RxPackets   float64   `json:"port_24-rx_packets,omitempty"`
				Port24RxBytes     int       `json:"port_24-rx_bytes,omitempty"`
				Port24RxDropped   float64   `json:"port_24-rx_dropped,omitempty"`
				Port24TxPackets   int       `json:"port_24-tx_packets,omitempty"`
				Port24TxBytes     int       `json:"port_24-tx_bytes,omitempty"`
				Port24RxMulticast float64   `json:"port_24-rx_multicast,omitempty"`
				Port24RxBroadcast float64   `json:"port_24-rx_broadcast,omitempty"`
				Port24TxMulticast float64   `json:"port_24-tx_multicast,omitempty"`
				Port24TxBroadcast float64   `json:"port_24-tx_broadcast,omitempty"`
				Port31RxPackets   float64   `json:"port_31-rx_packets,omitempty"`
				Port31RxBytes     int       `json:"port_31-rx_bytes,omitempty"`
				Port31RxDropped   float64   `json:"port_31-rx_dropped,omitempty"`
				Port31TxPackets   float64   `json:"port_31-tx_packets,omitempty"`
				Port31TxBytes     int64     `json:"port_31-tx_bytes,omitempty"`
				Port31RxMulticast float64   `json:"port_31-rx_multicast,omitempty"`
				Port31RxBroadcast float64   `json:"port_31-rx_broadcast,omitempty"`
				Port31TxMulticast float64   `json:"port_31-tx_multicast,omitempty"`
				Port31TxBroadcast float64   `json:"port_31-tx_broadcast,omitempty"`
				Port32RxPackets   int       `json:"port_32-rx_packets,omitempty"`
				Port32RxBytes     int64     `json:"port_32-rx_bytes,omitempty"`
				Port32RxDropped   float64   `json:"port_32-rx_dropped,omitempty"`
				Port32TxPackets   int       `json:"port_32-tx_packets,omitempty"`
				Port32TxBytes     int64     `json:"port_32-tx_bytes,omitempty"`
				Port32RxMulticast float64   `json:"port_32-rx_multicast,omitempty"`
				Port32RxBroadcast float64   `json:"port_32-rx_broadcast,omitempty"`
				Port32TxMulticast float64   `json:"port_32-tx_multicast,omitempty"`
				Port32TxBroadcast float64   `json:"port_32-tx_broadcast,omitempty"`
				Port34RxPackets   float64   `json:"port_34-rx_packets,omitempty"`
				Port34RxBytes     int       `json:"port_34-rx_bytes,omitempty"`
				Port34RxDropped   float64   `json:"port_34-rx_dropped,omitempty"`
				Port34TxPackets   int       `json:"port_34-tx_packets,omitempty"`
				Port34TxBytes     int64     `json:"port_34-tx_bytes,omitempty"`
				Port34RxMulticast float64   `json:"port_34-rx_multicast,omitempty"`
				Port34RxBroadcast float64   `json:"port_34-rx_broadcast,omitempty"`
				Port34TxMulticast float64   `json:"port_34-tx_multicast,omitempty"`
				Port34TxBroadcast float64   `json:"port_34-tx_broadcast,omitempty"`
				Port36RxPackets   float64   `json:"port_36-rx_packets,omitempty"`
				Port36RxBytes     int       `json:"port_36-rx_bytes,omitempty"`
				Port36RxDropped   float64   `json:"port_36-rx_dropped,omitempty"`
				Port36TxPackets   float64   `json:"port_36-tx_packets,omitempty"`
				Port36TxBytes     int       `json:"port_36-tx_bytes,omitempty"`
				Port36RxMulticast float64   `json:"port_36-rx_multicast,omitempty"`
				Port36RxBroadcast float64   `json:"port_36-rx_broadcast,omitempty"`
				Port36TxMulticast float64   `json:"port_36-tx_multicast,omitempty"`
				Port36TxBroadcast float64   `json:"port_36-tx_broadcast,omitempty"`
				Port37RxPackets   float64   `json:"port_37-rx_packets,omitempty"`
				Port37RxBytes     int       `json:"port_37-rx_bytes,omitempty"`
				Port37TxPackets   int       `json:"port_37-tx_packets,omitempty"`
				Port37TxBytes     int       `json:"port_37-tx_bytes,omitempty"`
				Port37RxMulticast float64   `json:"port_37-rx_multicast,omitempty"`
				Port37RxBroadcast float64   `json:"port_37-rx_broadcast,omitempty"`
				Port37TxMulticast float64   `json:"port_37-tx_multicast,omitempty"`
				Port37TxBroadcast float64   `json:"port_37-tx_broadcast,omitempty"`
				Port39RxPackets   float64   `json:"port_39-rx_packets,omitempty"`
				Port39RxBytes     int       `json:"port_39-rx_bytes,omitempty"`
				Port39RxDropped   float64   `json:"port_39-rx_dropped,omitempty"`
				Port39TxPackets   float64   `json:"port_39-tx_packets,omitempty"`
				Port39TxBytes     int       `json:"port_39-tx_bytes,omitempty"`
				Port39RxMulticast float64   `json:"port_39-rx_multicast,omitempty"`
				Port39RxBroadcast float64   `json:"port_39-rx_broadcast,omitempty"`
				Port39TxMulticast float64   `json:"port_39-tx_multicast,omitempty"`
				Port39TxBroadcast float64   `json:"port_39-tx_broadcast,omitempty"`
				Port40TxPackets   int       `json:"port_40-tx_packets,omitempty"`
				Port40TxBytes     int64     `json:"port_40-tx_bytes,omitempty"`
				Port40TxMulticast float64   `json:"port_40-tx_multicast,omitempty"`
				Port40TxBroadcast float64   `json:"port_40-tx_broadcast,omitempty"`
				Port41RxPackets   float64   `json:"port_41-rx_packets,omitempty"`
				Port41RxBytes     int       `json:"port_41-rx_bytes,omitempty"`
				Port41RxDropped   float64   `json:"port_41-rx_dropped,omitempty"`
				Port41TxPackets   float64   `json:"port_41-tx_packets,omitempty"`
				Port41TxBytes     int       `json:"port_41-tx_bytes,omitempty"`
				Port41RxMulticast float64   `json:"port_41-rx_multicast,omitempty"`
				Port41RxBroadcast float64   `json:"port_41-rx_broadcast,omitempty"`
				Port41TxMulticast float64   `json:"port_41-tx_multicast,omitempty"`
				Port41TxBroadcast float64   `json:"port_41-tx_broadcast,omitempty"`
				Port42RxPackets   int       `json:"port_42-rx_packets,omitempty"`
				Port42RxBytes     int64     `json:"port_42-rx_bytes,omitempty"`
				Port42TxPackets   int       `json:"port_42-tx_packets,omitempty"`
				Port42TxBytes     int64     `json:"port_42-tx_bytes,omitempty"`
				Port42RxMulticast float64   `json:"port_42-rx_multicast,omitempty"`
				Port42RxBroadcast float64   `json:"port_42-rx_broadcast,omitempty"`
				Port42TxMulticast float64   `json:"port_42-tx_multicast,omitempty"`
				Port42TxBroadcast float64   `json:"port_42-tx_broadcast,omitempty"`
				Port44RxPackets   float64   `json:"port_44-rx_packets,omitempty"`
				Port44RxBytes     int       `json:"port_44-rx_bytes,omitempty"`
				Port44TxPackets   int       `json:"port_44-tx_packets,omitempty"`
				Port44TxBytes     int       `json:"port_44-tx_bytes,omitempty"`
				Port44RxBroadcast float64   `json:"port_44-rx_broadcast,omitempty"`
				Port44TxMulticast float64   `json:"port_44-tx_multicast,omitempty"`
				Port44TxBroadcast float64   `json:"port_44-tx_broadcast,omitempty"`
				Port45RxPackets   float64   `json:"port_45-rx_packets,omitempty"`
				Port45RxBytes     int       `json:"port_45-rx_bytes,omitempty"`
				Port45RxDropped   float64   `json:"port_45-rx_dropped,omitempty"`
				Port45TxPackets   int       `json:"port_45-tx_packets,omitempty"`
				Port45TxBytes     int       `json:"port_45-tx_bytes,omitempty"`
				Port45RxMulticast float64   `json:"port_45-rx_multicast,omitempty"`
				Port45RxBroadcast float64   `json:"port_45-rx_broadcast,omitempty"`
				Port45TxMulticast float64   `json:"port_45-tx_multicast,omitempty"`
				Port45TxBroadcast float64   `json:"port_45-tx_broadcast,omitempty"`
				Port46RxPackets   float64   `json:"port_46-rx_packets,omitempty"`
				Port46RxBytes     int       `json:"port_46-rx_bytes,omitempty"`
				Port46RxDropped   float64   `json:"port_46-rx_dropped,omitempty"`
				Port46TxPackets   float64   `json:"port_46-tx_packets,omitempty"`
				Port46TxBytes     int       `json:"port_46-tx_bytes,omitempty"`
				Port46RxMulticast float64   `json:"port_46-rx_multicast,omitempty"`
				Port46RxBroadcast float64   `json:"port_46-rx_broadcast,omitempty"`
				Port46TxMulticast float64   `json:"port_46-tx_multicast,omitempty"`
				Port46TxBroadcast float64   `json:"port_46-tx_broadcast,omitempty"`
				Port47RxPackets   int       `json:"port_47-rx_packets,omitempty"`
				Port47RxBytes     int64     `json:"port_47-rx_bytes,omitempty"`
				Port47RxDropped   float64   `json:"port_47-rx_dropped,omitempty"`
				Port47TxPackets   int       `json:"port_47-tx_packets,omitempty"`
				Port47TxBytes     int64     `json:"port_47-tx_bytes,omitempty"`
				Port47RxMulticast float64   `json:"port_47-rx_multicast,omitempty"`
				Port47RxBroadcast float64   `json:"port_47-rx_broadcast,omitempty"`
				Port47TxMulticast float64   `json:"port_47-tx_multicast,omitempty"`
				Port47TxBroadcast float64   `json:"port_47-tx_broadcast,omitempty"`
				Port48RxPackets   float64   `json:"port_48-rx_packets,omitempty"`
				Port48RxBytes     int       `json:"port_48-rx_bytes,omitempty"`
				Port48RxDropped   float64   `json:"port_48-rx_dropped,omitempty"`
				Port48TxPackets   float64   `json:"port_48-tx_packets,omitempty"`
				Port48TxBytes     int       `json:"port_48-tx_bytes,omitempty"`
				Port48RxMulticast float64   `json:"port_48-rx_multicast,omitempty"`
				Port48TxMulticast float64   `json:"port_48-tx_multicast,omitempty"`
				Port48TxBroadcast float64   `json:"port_48-tx_broadcast,omitempty"`
				Port51RxPackets   int       `json:"port_51-rx_packets,omitempty"`
				Port51RxBytes     int64     `json:"port_51-rx_bytes,omitempty"`
				Port51TxPackets   int       `json:"port_51-tx_packets,omitempty"`
				Port51TxBytes     int64     `json:"port_51-tx_bytes,omitempty"`
				Port51RxMulticast float64   `json:"port_51-rx_multicast,omitempty"`
				Port51RxBroadcast float64   `json:"port_51-rx_broadcast,omitempty"`
				Port51TxMulticast float64   `json:"port_51-tx_multicast,omitempty"`
				Port51TxBroadcast float64   `json:"port_51-tx_broadcast,omitempty"`
				Port44RxMulticast float64   `json:"port_44-rx_multicast,omitempty"`
				Port48RxBroadcast float64   `json:"port_48-rx_broadcast,omitempty"`
				Port42RxDropped   float64   `json:"port_42-rx_dropped,omitempty"`
				Port51RxDropped   float64   `json:"port_51-rx_dropped,omitempty"`
				Port44RxDropped   float64   `json:"port_44-rx_dropped,omitempty"`
				Port9RxPackets    float64   `json:"port_9-rx_packets,omitempty"`
				Port9RxBytes      int       `json:"port_9-rx_bytes,omitempty"`
				Port9RxMulticast  float64   `json:"port_9-rx_multicast,omitempty"`
				Port9RxBroadcast  float64   `json:"port_9-rx_broadcast,omitempty"`
				Port9RxDropped    float64   `json:"port_9-rx_dropped,omitempty"`
				Port22RxPackets   float64   `json:"port_22-rx_packets,omitempty"`
				Port22RxBytes     int       `json:"port_22-rx_bytes,omitempty"`
				Port22RxDropped   float64   `json:"port_22-rx_dropped,omitempty"`
				Port22RxMulticast float64   `json:"port_22-rx_multicast,omitempty"`
				Port22RxBroadcast float64   `json:"port_22-rx_broadcast,omitempty"`
				Port18RxPackets   float64   `json:"port_18-rx_packets,omitempty"`
				Port18RxBytes     int       `json:"port_18-rx_bytes,omitempty"`
				Port18RxMulticast float64   `json:"port_18-rx_multicast,omitempty"`
				Port18RxBroadcast float64   `json:"port_18-rx_broadcast,omitempty"`
				Port18RxDropped   float64   `json:"port_18-rx_dropped,omitempty"`
				Port40RxPackets   float64   `json:"port_40-rx_packets,omitempty"`
				Port40RxBytes     int       `json:"port_40-rx_bytes,omitempty"`
				Port40RxDropped   float64   `json:"port_40-rx_dropped,omitempty"`
				Port40RxMulticast float64   `json:"port_40-rx_multicast,omitempty"`
				Port40RxBroadcast float64   `json:"port_40-rx_broadcast,omitempty"`
				Port18TxDropped   float64   `json:"port_18-tx_dropped,omitempty"`
				Port33TxPackets   int       `json:"port_33-tx_packets,omitempty"`
				Port33TxBytes     int       `json:"port_33-tx_bytes,omitempty"`
				Port33TxMulticast float64   `json:"port_33-tx_multicast,omitempty"`
				Port33RxPackets   float64   `json:"port_33-rx_packets,omitempty"`
				Port33RxBytes     int       `json:"port_33-rx_bytes,omitempty"`
				Port33RxMulticast float64   `json:"port_33-rx_multicast,omitempty"`
				Port33RxBroadcast float64   `json:"port_33-rx_broadcast,omitempty"`
				Port33TxBroadcast float64   `json:"port_33-tx_broadcast,omitempty"`
				Port33RxDropped   float64   `json:"port_33-rx_dropped,omitempty"`
				Port37RxDropped   float64   `json:"port_37-rx_dropped,omitempty"`
				Port5TxPackets    float64   `json:"port_5-tx_packets,omitempty"`
				Port5TxBytes      int64     `json:"port_5-tx_bytes,omitempty"`
				Port5TxMulticast  float64   `json:"port_5-tx_multicast,omitempty"`
				Port5TxBroadcast  float64   `json:"port_5-tx_broadcast,omitempty"`
				Port5RxPackets    float64   `json:"port_5-rx_packets,omitempty"`
				Port5RxBytes      int       `json:"port_5-rx_bytes,omitempty"`
				Port5RxMulticast  float64   `json:"port_5-rx_multicast,omitempty"`
				Port5RxDropped    float64   `json:"port_5-rx_dropped,omitempty"`
				Port5RxBroadcast  float64   `json:"port_5-rx_broadcast,omitempty"`
				Port51TxDropped   float64   `json:"port_51-tx_dropped,omitempty"`
				Port2RxPackets    float64   `json:"port_2-rx_packets,omitempty"`
				Port2RxBytes      int       `json:"port_2-rx_bytes,omitempty"`
				Port2TxPackets    float64   `json:"port_2-tx_packets,omitempty"`
				Port2TxBytes      int64     `json:"port_2-tx_bytes,omitempty"`
				Port2RxMulticast  float64   `json:"port_2-rx_multicast,omitempty"`
				Port2RxBroadcast  float64   `json:"port_2-rx_broadcast,omitempty"`
				Port2TxMulticast  float64   `json:"port_2-tx_multicast,omitempty"`
				Port2RxDropped    float64   `json:"port_2-rx_dropped,omitempty"`
				Port2TxBroadcast  float64   `json:"port_2-tx_broadcast,omitempty"`
				Port48TxDropped   float64   `json:"port_48-tx_dropped,omitempty"`
				Port22TxDropped   float64   `json:"port_22-tx_dropped,omitempty"`
			} `json:"sw,omitempty"`
		} `json:"stat,omitempty"`
	} `json:"data,omitempty"`
}
